// dsh-russian-lang — браузерная половина. ФАЙЛ СГЕНЕРИРОВАН, правьте ru/*.json
// и ru-plugins/*.json и запускайте build.py.
//
// Плагин докладывает русский словарь в чужие namespace'ы: реестр локалей это
// разрешает — register(ns, locale, dict) конфликтует только если пара
// (namespace, язык) уже занята, а "ru" не занимает никто.
//
// Ядро без русского: список языков для селектора и setLocale() зашит в
// @deepseek-ai/dsh-client-locale (zh/en). Поэтому переключатель плагина
// активирует русский публичным методом runtime (publish), а не через ядро —
// ничьи файлы не патчатся. Если ядро узнает "ru" само (список расширят),
// плагин пойдёт штатным setLocale().
window.__ModuleLoader__.load({
  id: '@goodandready/dsh-russian-lang',
  factory: (require) => {
    var module = { exports: {} }
    const React = require('react')

    /** namespace -> { ключ: перевод } */
    const RU = {
 "betterSidebar": {
  "addPluginsBrowseMore": "Ещё плагины на GitHub (тема: dsh-better-sidebar)",
  "addPluginsEmpty": "Подборки пока нет — опубликуйте свой плагин под темой на GitHub",
  "addPluginsRecommended": "Рекомендуемые плагины",
  "addPluginsTabCard": "Добавить плагины вкладок",
  "addPluginsTabCardDesc": "Зарегистрировать новую страницу панели",
  "addPluginsTabDesc": "Страницы панели (вкладки) расширяются плагинами. Плагины регистрируются через сервис ctx.betterSidebar; кнопка «Установить» копирует команду — вставьте её в терминал на машине с профилем DSH и выполните.",
  "addPluginsViewerCard": "Добавить плагины предпросмотра",
  "addPluginsViewerCardDesc": "Зарегистрировать просмотр нового типа файлов",
  "addPluginsViewerDesc": "Просмотрщики файлов расширяются плагинами. Плагины регистрируются через сервис ctx.betterSidebar; кнопка «Установить» копирует команду — вставьте её в терминал на машине с профилем DSH и выполните.",
  "addToConversation": "Добавить в диалог",
  "binary": "Двоичный файл, предпросмотр недоступен",
  "binaryNoPreview": "Этот тип файлов нельзя показать",
  "branch": "Ветка",
  "brokenSymlink": "Битая ссылка",
  "browser": "Браузер",
  "browserBack": "Назад",
  "browserBlockedLoopback": "Заблокировано: локальные и внутренние адреса здесь открывать нельзя",
  "browserBlockedScheme": "Заблокировано: разрешены только адреса http и https",
  "browserEmbedAnyway": "Всё равно загрузить",
  "browserEmbedBlocked": "{host} запрещает встраивание",
  "browserEmbedBlockedDesc": "Сайт запрещает показывать себя внутри других страниц (X-Frame-Options / frame-ancestors), поэтому в панели он не откроется. Откройте его в обычном браузере.",
  "browserForward": "Вперёд",
  "browserGo": "Перейти",
  "browserInvalid": "Неверный адрес",
  "browserNoSandboxWarning": "Песочница выключена: страница работает с полными правами интерфейса (включить обратно можно в настройках)",
  "browserOpenExternal": "Открыть в браузере",
  "browserPlaceholder": "Введите адрес, например example.com",
  "browserStart": "Введите адрес, чтобы начать (режим песочницы)",
  "cancel": "Отмена",
  "changes": "Изменения",
  "checkoutError": "Переключить ветку не удалось",
  "cherryPickCommit": "Перенести коммит",
  "cherryPickDesc": "Применить изменения «{subject}» к текущей ветке.",
  "cherryPickTitle": "Перенос коммита",
  "close": "Закрыть",
  "collapse": "Свернуть панель",
  "collapseBottomPanel": "Свернуть нижнюю панель",
  "commit": "Закоммитить",
  "commitError": "Коммит не удался",
  "commitPlaceholder": "Сообщение коммита (Ctrl+Enter)",
  "copied": "Скопировано",
  "copy": "Копировать",
  "copyAbsolute": "Копировать абсолютный путь",
  "copyFullHash": "Копировать полный хеш",
  "copyInstall": "Копировать команду установки",
  "copyRelative": "Копировать относительный путь",
  "copyShortHash": "Копировать короткий хеш",
  "copySubject": "Копировать заголовок",
  "diffAdded": "Добавлено",
  "diffBinary": "Двоичный",
  "diffCollapse": "Свернуть",
  "diffDeleted": "Удалено",
  "diffEmpty": "Текстовых изменений нет",
  "diffExpand": "Показать ещё строк: {count}",
  "diffLoadError": "Не удалось загрузить различия",
  "diffRenamed": "Переименовано",
  "discard": "Отменить изменения",
  "discardDesc": "Изменения «{path}» в рабочем дереве будут отброшены без возможности вернуть.",
  "discardTitle": "Отмена изменений",
  "disconnected": "Терминал отключился, переподключаемся…",
  "download": "Скачать",
  "downloadToView": "Скачать, чтобы посмотреть",
  "edit": "Изменить",
  "editor": "Редактор",
  "editorEmptyHint": "Выберите файл в дереве или введите путь выше, чтобы открыть предпросмотр",
  "editorExplorer": "Как открывать файлы",
  "editorExplorerDesc": "Управляет поведением при открытии файлов",
  "editorExplorerMerged": "В одном окне",
  "editorExplorerMergedDesc": "Файлы сменяются в том же окне; новые окна открываются с деревом",
  "editorExplorerSplit": "Раздельно",
  "editorExplorerSplitDesc": "Окно без пути — это отдельный проводник (только дерево); каждый файл открывается своим окном (дерево пристыковано и по умолчанию закрыто)",
  "editorPathPlaceholder": "Путь к файлу (от папки сессии или абсолютный), Enter — открыть",
  "editorSearchNoResults": "Подходящих файлов нет",
  "editorSearchPlaceholder": "Поиск файлов по имени…",
  "editorSearchTruncated": "Слишком много совпадений — показана часть",
  "editorTreeToggle": "Дерево файлов",
  "error": "Не удалось загрузить",
  "exited": "Процесс терминала завершился",
  "expand": "Развернуть панель",
  "expandBottomPanel": "Развернуть нижнюю панель",
  "explorer": "Проводник",
  "files": "Файлы",
  "git": "Контроль версий",
  "gitDetail": "Посмотреть изменения",
  "hiddenFiles": "Скрытые файлы",
  "history": "История",
  "historyLoadError": "Не удалось догрузить историю",
  "htmlNoSandboxWarning": "Песочница выключена: этот HTML работает с полными правами интерфейса (включить обратно можно в настройках)",
  "jobDurationHours": "{hours} ч {minutes} мин",
  "jobDurationMinutes": "{minutes} мин {seconds} с",
  "jobDurationSeconds": "{seconds} с",
  "jobHideOutput": "Скрыть вывод",
  "jobKill": "Прервать",
  "jobKillConfirm": "Нажмите ещё раз для подтверждения",
  "jobKillError": "Прервать не удалось",
  "jobNoOutput": "Вывода пока нет",
  "jobNotReadYet": "Ждём, пока модель прочитает эту задачу; вывод появится здесь после вызова job_output",
  "jobOutputError": "Не удалось прочитать вывод",
  "jobOutputTruncated": "Вывод обрезан",
  "jobStatusCompleted": "Завершена",
  "jobStatusFailed": "Ошибка",
  "jobStatusKilled": "Прервана",
  "jobStatusRunning": "Выполняется",
  "jobStatusStopping": "Останавливается",
  "jobViewOutput": "Посмотреть вывод",
  "jobs": "Фоновые задачи",
  "jobsCount": "фоновых задач: {count}",
  "jobsCountRunning": "фоновых задач: {count} · выполняется: {running}",
  "loadMore": "Показать ещё",
  "loading": "Загрузка…",
  "newFile": "Новый файл",
  "newTab": "Новая вкладка",
  "newTerminal": "Новый терминал",
  "noChanges": "Изменений нет",
  "noSession": "Выберите диалог, чтобы пользоваться панелью",
  "notRepo": "Эта папка не является репозиторием git",
  "openEditor": "Открыть редактор",
  "openExplorer": "Проводник",
  "openFileNewTab": "Открыть в новой вкладке",
  "openFileSide": "Открыть сбоку",
  "openGit": "Панель git",
  "openPlugin": "Открыть",
  "openSubagent": "Задачи",
  "parent": "Родительская папка",
  "pluginGitRemotesDesc": "Вкладка Git Remotes: ветка, upstream, отставание и опережение, fetch (с необязательным prune), pull только ff-only и push после подтверждения во вкладке. Не заменяет встроенную вкладку git со стадированием и коммитами, не предлагает force-push и не даёт модели инструмент автопуша",
  "pluginNotLoaded": "Плагин не загружен, вкладка недоступна:",
  "pluginOfficeDesc": "Предпросмотр офисных файлов (.docx / .xlsx / .pptx) в редакторе better-sidebar; тяжёлые библиотеки рендеринга держатся вне основного бандла",
  "pluginSentinelDesc": "Пробуждение агента по условию: датчики файлов, процессов, портов, http, команд и вебхуков будят спящие сессии, когда условие сработало; добавляет вкладку Sentinel с общей таблицей наблюдений",
  "pluginSidebarQaDesc": "Выделил и спросил: выделите текст в диалоге, задайте вопрос в правой панели — откроется отдельная сессия-уточнение в той же рабочей папке; быстрая модель без рассуждений сжимает основной контекст и подставляет его вместе с цитатой, не прерывая основной диалог. Уточнения вкладываются, продолжаются и уходят в архив",
  "pluginVideoPreviewDesc": "Просмотр видео (.mp4/.webm/.mov/.mkv/.avi и других) прямо в редакторе better-sidebar через отдельный маршрут /video с поддержкой HTTP Range (206) — перемотка работает, ограничение mediaLimit в 20 МБ не действует",
  "preview": "Предпросмотр",
  "produced": "Создано",
  "producedOpen": "Открыть в панели",
  "referenceFile": "@файл",
  "refresh": "Обновить",
  "retry": "Повторить",
  "revertCommit": "Откатить коммит",
  "revertDesc": "Создать в текущей ветке новый коммит, отменяющий «{subject}».",
  "revertTitle": "Откат коммита",
  "sandboxRestore": "Вернуть песочницу",
  "sandboxStatusOn": "Песочница включена · страницы не видят данные интерфейса и локальные файлы; входы и сторонние куки могут не работать",
  "sandboxUnlock": "Временно отключить (небезопасно)",
  "save": "Сохранить",
  "saveFailed": "Сохранить не удалось",
  "saved": "Сохранено",
  "settingsBottomTerminalDesc": "При первом разворачивании нижней панели в сессии открывать в ней новый терминал (ограничение на число терминалов сохраняется; по умолчанию включено)",
  "settingsBottomTerminalTitle": "Открывать терминал при первом разворачивании нижней панели",
  "settingsBrowserHttpDesc": "Если включено, клик по внешней http-ссылке в диалоге или интерфейсе открывает панель (страницы плагинов с urlTarget имеют приоритет); Ctrl/Cmd+клик всегда в обход",
  "settingsBrowserHttpTitle": "Открывать http-страницы в панели",
  "settingsBrowserHttpsDesc": "Если включено, клик по внешней https-ссылке открывает панель. По умолчанию выключено: большинство https-сайтов запрещают встраивание, поэтому системный браузер удобнее",
  "settingsBrowserHttpsTitle": "Открывать https-страницы в панели",
  "settingsBrowserLinksDesc": "Если включено, клик по внешней ссылке открывает панель, а не новое окно; http и https управляются отдельными переключателями ниже; Ctrl/Cmd+клик всегда в обход",
  "settingsBrowserLinksTitle": "Открывать внешние ссылки из диалога в панели",
  "settingsBrowserSandboxDesc": "С выключенной песочницей любой открытый сайт работает в том же origin, что и интерфейс: он может читать данные сессии и действовать от вашего имени. Включайте только для полностью доверенных сайтов",
  "settingsBrowserSandboxTitle": "Отключить песочницу браузера (небезопасно)",
  "settingsConflict": "Настройку изменили в другом окне — повторите",
  "settingsDone": "Готово",
  "settingsFontFamilyDesc": "Своя гарнитура терминала (CSS-стек вида \"JetBrains Mono\", monospace; пусто — моноширинный шрифт темы)",
  "settingsFontFamilyPlaceholder": "\"JetBrains Mono\", monospace",
  "settingsFontFamilyTitle": "Шрифт терминала",
  "settingsFontSizeDesc": "Размер шрифта терминала в пикселях (9–32, по умолчанию 13)",
  "settingsFontSizeSuffix": "px",
  "settingsFontSizeTitle": "Размер шрифта терминала",
  "settingsGeneralTitle": "Общие",
  "settingsHtmlDefaultUnsafeDesc": "Если включено, каждый новый предпросмотр HTML открывается без песочницы (тот же origin, что и интерфейс — доступны файлы сессии и внутренние API); вернуть песочницу можно одним нажатием в строке состояния",
  "settingsHtmlDefaultUnsafeTitle": "Открывать предпросмотр HTML без песочницы (небезопасно)",
  "settingsHtmlSandboxDesc": "С выключенной песочницей просматриваемый HTML работает в том же origin, что и интерфейс: он может читать файлы сессии, локальное хранилище и вызывать внутренние API. Включайте только для полностью доверенных файлов",
  "settingsHtmlSandboxTitle": "Отключить песочницу предпросмотра HTML (небезопасно)",
  "settingsIntro": "Что показывает боковая панель и как она себя ведёт",
  "settingsJobsDesc": "Разворачивать панель и открывать страницу задач при появлении новой фоновой задачи в текущем диалоге (срабатывает на каждую); выключите, чтобы открывать вручную",
  "settingsJobsTitle": "Открывать страницу задач при новой фоновой задаче",
  "settingsNav": "Боковая панель",
  "settingsOpenDesc": "Разворачивать панель для совсем новых диалогов; у существующих сохраняется своя раскладка",
  "settingsOpenPathDesc": "Открывать файловые ссылки из диалога (строки инструментов, созданные файлы, упоминания) в редакторе панели, а не в системном приложении",
  "settingsOpenPathTitle": "Открывать файлы из диалога в панели",
  "settingsOpenTitle": "Разворачивать для новых диалогов",
  "settingsPopup": "Настройки функции",
  "settingsPopupDesc": "Параметры для «{feature}»",
  "settingsSaveFailed": "Не удалось сохранить",
  "settingsSubagentDesc": "Разворачивать панель и открывать страницу задач, когда в диалоге появляется субагент; выключите, чтобы открывать вручную",
  "settingsSubagentTitle": "Открывать страницу задач при появлении субагента",
  "settingsTabsTitle": "Содержимое панели",
  "settingsTitleBarDesc": "Оставлять место под системный заголовок окна Windows справа сверху, чтобы кнопки и содержимое панели располагались ниже, а не под ним",
  "settingsTitleBarStripDesc": "Высота полосы заголовка: на сколько пикселей опускаются кнопки и содержимое панели (0–120, по умолчанию 40)",
  "settingsTitleBarStripTitle": "Смещение",
  "settingsTitleBarTitle": "Режим совместимости с заголовком окна",
  "settingsToolsDesc": "Если включено, модель может создавать терминалы в панели и работать в них через восемь инструментов terminal_* (по умолчанию выключено)",
  "settingsToolsTitle": "Дать модели инструменты терминала",
  "settingsViewerCatchAll": "На всё остальное: любой файл",
  "settingsViewersTitle": "Просмотрщики файлов",
  "settingsWidthDesc": "Какую долю ширины окна занимает панель в новых диалогах (20–60)",
  "settingsWidthSuffix": "%",
  "settingsWidthTitle": "Ширина по умолчанию",
  "splitDown": "Разделить вниз",
  "splitLeft": "Разделить влево",
  "splitRight": "Разделить вправо",
  "splitUp": "Разделить вверх",
  "stage": "В индекс",
  "stageAll": "Всё в индекс",
  "staged": "В индексе",
  "subagent": "Задачи",
  "subagentCount": "субагентов: {count}",
  "subagentCountRunning": "субагентов: {count} · работает: {running}",
  "subagentDiagCorrupt": "Повреждён",
  "subagentDiagUnavailable": "Недоступен",
  "subagentDiagUnsupported": "Не поддерживается",
  "subagentEmpty": "Субагентов нет",
  "subagentEmptyDesc": "Здесь появятся субагенты, запущенные основным агентом",
  "subagentInactive": "Простаивает",
  "subagentMainAgent": "Основной агент",
  "subagentModeContinuable": "С продолжением",
  "subagentModeOneShot": "Разовый",
  "subagentRunning": "Работает",
  "subagentThinking": "Думает…",
  "terminal": "Терминал",
  "terminalConnectFailed": "Терминал не смог подключиться несколько раз подряд",
  "terminalDepsFailed": "Не удалось загрузить зависимость терминала node-pty",
  "terminalDepsHint": "Выполните команду ниже в терминале на машине с DSH, чтобы починить, и повторите (версия node-pty должна совпадать с версией ядра DSH):",
  "terminalDepsProfile": " (определён профиль: {profile})",
  "terminalError": "Не удалось подключиться к терминалу",
  "terminalLimit": "Достигнут предел терминалов (3)",
  "terminalRetry": "Повторить",
  "timeHoursAgo": "{n} ч назад",
  "timeJustNow": "только что",
  "timeMinutesAgo": "{n} мин назад",
  "timeYesterday": "вчера",
  "truncation": "Файл слишком большой — показаны первые 512 КБ",
  "unsaved": "Не сохранено",
  "unstage": "Из индекса",
  "unstageAll": "Всё из индекса",
  "unstaged": "Вне индекса",
  "viewCommitDiff": "Посмотреть изменения коммита",
  "viewerBinary": "Скачивание файла",
  "viewerCode": "Код",
  "viewerHtml": "HTML",
  "viewerImage": "Изображение",
  "viewerMarkdown": "Markdown",
  "viewerPdf": "PDF"
 },
 "command": {
  "listbox.aria": "Совпадения /{command}",
  "notice.imagesUnsupported": "/{command} не принимает вложения-изображения — сначала удалите их",
  "overlay.aria": "Параметры /{command}",
  "search.aria": "Фильтр параметров",
  "search.placeholder": "Поиск…",
  "status.applying": "Применение…",
  "status.empty": "Нет параметров",
  "status.loading": "Загрузка параметров…"
 },
 "common": {
  "back": "Назад",
  "cancel": "Отмена",
  "close": "Закрыть",
  "collapse": "Свернуть",
  "copied": "Скопировано",
  "copy": "Копировать",
  "delete": "Удалить",
  "edit": "Изменить",
  "expand": "Развернуть",
  "load.failed": "Не удалось загрузить",
  "loading": "Загрузка…",
  "more": "Ещё",
  "next": "Дальше",
  "none": "Нет",
  "ok": "ОК",
  "previous": "Назад",
  "retry": "Повторить",
  "save": "Сохранить",
  "search": "Поиск",
  "skip": "Пропустить",
  "submit": "Отправить",
  "submitting": "Отправка…",
  "truncated": "Обрезано",
  "unknown": "Неизвестно"
 },
 "context-doctor": {
  "cd.attention": "Стоит посмотреть",
  "cd.catalog": "{n} скиллов",
  "cd.empty": "Данных пока нет",
  "cd.error": "Проверка не удалась",
  "cd.files": "файлов",
  "cd.guideline": "из 50k",
  "cd.healthy": "В норме",
  "cd.healthyHint": "Контекст расходуется экономно и укладывается в рекомендованный бюджет.",
  "cd.hint": "Открыть аудит контекста",
  "cd.instructions": "Цепочка инструкций",
  "cd.loading": "Проверка…",
  "cd.mcp": "Инструменты MCP",
  "cd.mcpTools": "{n} инструментов",
  "cd.refresh": "Обновить",
  "cd.residentTokens": "Проверка бюджета контекста",
  "cd.review": "Стоит посмотреть",
  "cd.reviewHint": "Некоторые части контекста стоит пересмотреть, пока они не стали дорогими.",
  "cd.skills": "Каталог скиллов",
  "cd.suggestions": "{n} рекомендаций",
  "cd.title": "Аудит контекста",
  "cd.tools": "Схемы инструментов",
  "cd.toolsCount": "инструментов",
  "cd.updated": "Обновлено"
 },
 "conversation": {
  "access.confirm.acknowledge": "Я понимаю риски и хочу продолжить",
  "access.confirm.cancel": "Отмена",
  "access.confirm.description": "Полный доступ убирает часть подтверждений и позволяет агенту действовать напрямую, включая чувствительные операции, изменение файлов и внешние команды. Включайте, только если доверяете текущей задаче.",
  "access.confirm.enable": "Включить полный доступ",
  "access.confirm.title": "Включить полный доступ?",
  "approval.allowOnce": "Разрешить один раз",
  "approval.detail.aria": "Подробности запроса",
  "approval.escalation": "Инструмент {toolName} просит повышенных прав",
  "approval.reject": "Отклонить",
  "approval.waiting": "Ожидание подтверждения",
  "ask.answered": "{answered}/{total} отвечено",
  "ask.cancelled": "отменено",
  "ask.interrupted": "прервано",
  "ask.rowTitle": "Вопрос",
  "ask.waiting": "ожидание",
  "bash.failed": "Ошибка",
  "bash.running": "Выполняется",
  "bash.stopped": "Остановлено",
  "chat.loadError": "Не удалось загрузить историю: {message} ({code})",
  "chat.loadOlder": "Загрузить раньше",
  "chat.loadingHistory": "Загрузка истории…",
  "chat.toBottom": "Вниз",
  "clock.md": "{d}.{m}",
  "clock.ymd": "{d}.{m}.{y}",
  "command.done": "Готово",
  "command.failed": "Команда не выполнена",
  "command.imagesUnsupported": "/{command} не принимает вложения-изображения — сначала удалите их",
  "command.running": "Выполняется…",
  "command.title": "Команда",
  "context.aria": "{percent} контекста занято",
  "context.messages": "Сообщения",
  "context.system": "Системный промпт",
  "context.tools": "Инструменты",
  "context.used": "контекста занято",
  "details.close": "Закрыть подробности",
  "details.empty": "Выберите строку инструмента в переписке, чтобы увидеть подробности",
  "details.input": "Вход",
  "details.notInWindow": "Этот вызов вне текущего окна",
  "details.output": "Выход",
  "details.running": "Выполняется…",
  "details.title": "Подробности",
  "duration.minutes": "{minutes} мин {seconds} с",
  "duration.seconds": "{seconds} с",
  "fileOpen.folderTitle": "Не удалось открыть папку",
  "fileOpen.folderUnknown": "Не удалось открыть эту папку",
  "fileOpen.title": "Не удалось открыть файл",
  "fileOpen.unknown": "Не удалось открыть этот файл",
  "hero.chooseWorkspace": "Выбрать рабочую папку",
  "hero.headline": "Навстречу неизвестному",
  "hero.preview": "Предпросмотр",
  "hint.goal": "опишите цель длительной задачи",
  "hint.goal.active": "цель активна — изменить / пауза / продолжить / снять",
  "image.closePreview": "Закрыть просмотр оригинала",
  "image.dimensionTooLarge": "Стороны изображения не больше {size}px — уменьшите его и попробуйте снова",
  "image.dropBlocked": "Сейчас картинки добавить нельзя",
  "image.dropDesc": "До {count} изображений, каждое до {size}",
  "image.dropTitle": "Перетащите изображения сюда",
  "image.fileTooLarge": "Каждое изображение должно быть меньше {size}",
  "image.label": "Изображение",
  "image.loadFailed": "Изображение не загрузилось, нажмите для повтора",
  "image.loading": "Загрузка изображения…",
  "image.modelUnsupported": "Текущая модель не принимает изображения; выберите подходящую",
  "image.openOriginal": "Открыть оригинал",
  "image.openOriginalLabel": "{label}, нажмите, чтобы открыть оригинал",
  "image.original": "Оригинал",
  "image.pending": "Изображения к отправке",
  "image.preview": "Просмотр оригинала",
  "image.remove": "Убрать изображение {name}",
  "image.scrollLeft": "Прокрутить изображения влево",
  "image.scrollRight": "Прокрутить изображения вправо",
  "image.sendFailed": "Не удалось отправить изображения ({reason}); добавьте заново и повторите",
  "image.serviceUnavailable": "Служба загрузки изображений недоступна",
  "image.subagentUnsupported": "Сессии субагентов пока не поддерживают изображения",
  "image.tooMany": "В одно сообщение помещается до {count} изображений",
  "image.tooManyPixels": "Слишком большое разрешение; сожмите изображение и повторите",
  "image.totalTooLarge": "Изображения весят больше {size}; уберите часть и повторите",
  "image.unsupportedType": "Поддерживаются только PNG, JPG, WebP и GIF",
  "input.accessMode": "Режим доступа, сейчас: {name}",
  "input.commands": "Команды",
  "input.send": "Отправить сообщение",
  "input.stop": "Остановить генерацию",
  "json.truncated": "… обрезано, всего символов: {total}",
  "message.branch": "Ответвить новый диалог",
  "message.branchUnavailable": "Доступно только на последнем сообщении завершённого хода",
  "message.compaction": "Контекст сжат",
  "message.compaction.completed": "Сжато элементов истории: {items} (~{tokens} токенов)",
  "message.compaction.expand": "Показать итог сжатия",
  "message.compaction.running": "Сжатие контекста…",
  "message.compaction.unavailable": "Итог сжатия недоступен",
  "message.context.catalog.more": "… ещё {count}",
  "message.context.catalog.replaced": "Каталог заменён",
  "message.context.instructions.added": "добавлено",
  "message.context.instructions.loaded": "загружено",
  "message.context.instructions.removed": "удалено",
  "message.context.instructions.updated": "обновлено",
  "message.context.recall.counts": "{retained} оставлено · {omitted} пропущено",
  "message.context.recall.truncated": "обрезано",
  "message.context.relay.from": "Из сессии {session}",
  "message.context.snapshot.supersedes": "Заменяет прежние снимки",
  "message.contextInjection": "Инъекция контекста",
  "message.contextRecall": "Напоминание из сессии",
  "message.extraBlock": "Дополнительный блок",
  "message.maxTokens": "Достигнут лимит выходных токенов",
  "message.maxTokens.hint": "Ответ обрезан; написанное ранее сохранено в переписке. Отправьте «продолжай», чтобы модель дописала.",
  "message.ranFor": "Заняло {duration}",
  "message.referenceSeparator": ", ",
  "message.referenceSummary": "Упомянутая сессия · {labels}",
  "message.retry.active": "Повтор запроса к модели",
  "message.retry.cancelled": "Повтор запроса отменён",
  "message.retry.delay": "Задержка перед повтором: ",
  "message.retry.failure": "Причина сбоя: ",
  "message.retry.scheduled": "Ожидание повтора запроса",
  "message.retry.started": "Запрос к модели повторён",
  "message.retry.status": "{label} ({retry}/{maximum}) · {seconds} с",
  "message.stopped": "Остановлено",
  "message.tokensPerSecond": "{tps} ток/с",
  "message.ttft": "Первый токен {seconds} с",
  "message.turnError": "Ход не удался",
  "message.unknownBlock": "Неизвестный блок содержимого",
  "message.unknownSurface": "Неизвестное событие: {type}",
  "placeholder.default": "Напишите агенту",
  "placeholder.hero": "Опишите, что хотите сделать",
  "placeholder.parentOffline": "Родительская сессия офлайн: отправка недоступна, но остановить выполнение можно",
  "placeholder.steerQueue": "Cmd/Ctrl+Enter направит все сообщения из очереди",
  "placeholder.unavailable": "Сессия недоступна",
  "placeholder.workspace": "Выберите рабочую папку, чтобы начать",
  "queue.cancelEdit": "Отменить правку",
  "queue.count": "Сообщений в очереди: {n}",
  "queue.edit": "Изменить сообщение в очереди",
  "queue.edit.unsupported": "Содержит не только текст; правка пока не поддерживается",
  "queue.editFailed": "Не удалось изменить: сообщение, возможно, уже отправляется.",
  "queue.remove": "Убрать из очереди",
  "queue.removeFailed": "Не удалось убрать: сообщение, возможно, уже отправляется.",
  "queue.save": "Сохранить сообщение",
  "queue.steer": "Направить сообщение",
  "queue.steer.unavailable": "Направлять можно только пока агент работает",
  "queue.steerFailed": "Не удалось направить. Попробуйте ещё раз.",
  "row.failed": "Ошибка",
  "row.running": "Выполняется",
  "row.stopped": "Остановлено",
  "session.hierarchy": "Иерархия сессий",
  "settings.enter.description": "Только когда агент занят; Cmd/Ctrl+Enter даёт другое поведение",
  "settings.enter.queue": "В очередь",
  "settings.enter.steer": "Направить",
  "settings.enter.title": "Enter, когда агент занят",
  "stats.cacheHit": "Попаданий в кэш {percent}%",
  "stats.counts": "ходов: {turns} · шагов: {steps}",
  "stats.llm": "Модель {duration}",
  "stats.tokens": "Вход {input} ток · выход {output} ток",
  "stats.tokensPerSecond": "{throughput} ток/с",
  "stats.toolCall": "Инструменты {duration}",
  "stats.ttftAverage": "Первый токен в среднем {duration}",
  "terminal.collapseAria": "Свернуть вывод",
  "terminal.done": "Готово",
  "terminal.exitCode": "код возврата {code}",
  "terminal.expandAria": "Показать оставшиеся строки вывода: {n}",
  "terminal.expandRest": "… ещё строк: {n}",
  "terminal.failed": "Ошибка",
  "terminal.noOutput": "Вывода нет",
  "terminal.running": "Выполняется",
  "terminal.signal": "сигнал {signal}",
  "todo.completed": "{done}/{total} выполнено",
  "todo.progress.active": "{active} в работе",
  "todo.progress.done": "{done} выполнено",
  "todo.progress.pending": "{pending} в очереди",
  "todo.rowTitle": "Обновить список задач",
  "todo.title": "Задачи",
  "view.chat": "Чат"
 },
 "cordis": {
  "a11y.defining": "Определение плагина",
  "a11y.failed": "Определить не удалось",
  "a11y.stopped": "Определение прервано",
  "action.approve": "Разрешить",
  "action.approveOnce": "Разрешить только эту версию",
  "action.approvePlugin": "Разрешить будущие версии этого плагина",
  "action.decline": "Отклонить",
  "action.remove": "Удалить",
  "action.retry": "Повторить",
  "action.rollback": "Откатить",
  "action.run": "Запустить",
  "action.stop": "Остановить",
  "body.clientCode": "Клиент",
  "body.copied": "Скопировано",
  "body.copy": "Копировать",
  "body.hostCode": "Хост",
  "body.output": "Результат",
  "body.source": "Исходник плагина",
  "panel.approvals.aria": "Подтверждения Cordis",
  "panel.current": "Текущая: {packageId}",
  "panel.empty": "Плагинов пока нет",
  "panel.group.current": "Эта сессия",
  "panel.group.others": "Другие сессии",
  "panel.hint": "Управление запуском — в панели Cordis над настройками",
  "panel.loading": "Чтение…",
  "panel.next": "Следующая: {packageId}",
  "panel.plugins.aria": "Плагины Cordis",
  "panel.readFailed": "Не удалось прочитать список плагинов: {message}",
  "panel.runningCount": "работает: {count}",
  "panel.title": "Плагины Cordis",
  "panel.trigger": "Плагин Cordis",
  "panel.version": "Версия",
  "purpose.missing": "(назначение не указано)",
  "render.failedAbdicated": "Отрисовка в {slot} не удалась, вернули стандартный интерфейс:",
  "render.failedHeld": "Отрисовка в {slot} не удалась:",
  "row.defineTitle": "Зарегистрировать плагин Cordis",
  "row.removeTitle": "Удалить плагин Cordis",
  "row.runTitle": "Запустить плагин Cordis",
  "row.stopTitle": "Остановить плагин Cordis",
  "row.updateTitle": "Обновить плагин Cordis",
  "run.removed": "Этого пакета больше нет",
  "run.superseded": "Ниже есть более свежая карточка запуска",
  "status.awaitingApproval": "Ждёт подтверждения",
  "status.clientPending": "Клиент готов к активации",
  "status.failed": "Запуск не удался",
  "status.idle": "Готов",
  "status.removed": "Удалён",
  "status.running": "Работает",
  "status.superseded": "Есть более свежий запуск"
 },
 "deliverables": {
  "produced.label": "Создано",
  "produced.more": "+ {count} файлов",
  "produced.moreOne": "+ 1 файл",
  "produced.open": "Открыть {name}",
  "produced.showInFolder": "Показать в папке"
 },
 "directory-browser": {
  "browser.cancel": "Отмена",
  "browser.create": "Создать",
  "browser.createIn": "Новая папка в «{name}»",
  "browser.editPath": "Изменить путь",
  "browser.folderName": "Имя папки",
  "browser.home": "Домашняя папка",
  "browser.loading": "Загрузка…",
  "browser.newFolder": "Новая папка",
  "browser.open": "Открыть",
  "browser.showHidden": "Показывать скрытые файлы",
  "browser.title": "Выбор рабочей папки",
  "browser.truncated": "Слишком много папок; показано только начало.",
  "browser.untitledFolder": "Без имени"
 },
 "dsh-market": {
  "actWhy": "Почему не активен?",
  "aiFix": "Починить с агентом",
  "aiFixConservative": "Действуй осторожно: чини только явные ошибки из списка выше (падения при запуске, дубли записей, подтверждённые расхождения зависимостей). Предупреждения и записи к сведению (например, неподтверждённые диапазоны peer-зависимостей) трогай, только если они связаны с явной ошибкой. Не делай лишних обновлений и перестановок; объясняй каждое изменение и жди подтверждения.",
  "aiFixCopied": "Промпт скопирован — вставьте его в новый диалог и отправьте, когда будете готовы",
  "aiFixFail": "Буфер обмена недоступен — скопируйте диагностику ниже вручную",
  "aiFixHint": "Передать диагностику новой сессии агента (скопировано в буфер; отправлять или нет — решаете вы)",
  "aiFixIntro": "Помоги починить проблемы с плагинами DeepSeek Harness (профиль: {0}). Диагностика показала:",
  "aiFixScope": "Можно менять порядок в dsh.profile.bundles, включать и выключать плагины, править cordis.patch.yml. Учти: официальные бандлы трогать нельзя; прежде чем что-то менять, изложи план.",
  "all": "Все",
  "alreadyInstalled": "✓ Установлен",
  "approveBuilds": "Разрешить сборочные скрипты и повторить",
  "autoBackup": "Резервная копия раз в сутки (при открытии маркета)",
  "backTop": "Наверх",
  "backupDone": "Копия загружена",
  "backupDownload": "Выгрузить копию",
  "backupHint": "Включает список плагинов и настройки профиля, но не node_modules. Восстановление ставит плагины заново по списку.",
  "backupImport": "Импортировать и посмотреть",
  "backupLocal": "Локальный файл",
  "backupWorking": "Выполняется…",
  "buildsSkipped": "Этому плагину нужны сборочные скрипты; по умолчанию они заблокированы ради безопасности. Разрешите их и переустановите:",
  "busyWait": "Уже выполняется другая операция — дождитесь её окончания (установка, обновление и удаление идут по одной)",
  "cancel": "Отмена",
  "cancelOp": "Отменить",
  "cancelled": "Отменено",
  "cancelling": "Отмена…",
  "catConflict": "Конфликты",
  "catDeps": "Зависимости",
  "catOrder": "Порядок",
  "catsLess": "Свернуть",
  "catsMore": "Ещё",
  "checkBundles": "Порядок загрузки плагинов",
  "checkBundlesEmpty": "Слои плагинов не объявлены",
  "checkCommunity": "сообщество",
  "checkDir": "каталог",
  "checkDuplicates": "Повторяющиеся записи плагинов",
  "checkDuplicatesEmpty": "Повторов нет",
  "checkEntries": "записей (идентификаторы загрузчика)",
  "checkErrors": "Ошибки",
  "checkErrorsEmpty": "Ошибок нет",
  "checkHoisted": "поднят",
  "checkIssues": "Найдены проблемы",
  "checkLoadFail": "Не удалось загрузить диагностику: ",
  "checkLoading": "Анализ профиля…",
  "checkMultiEmpty": "Пакетов ядра в нескольких версиях нет",
  "checkMultiVersion": "Пакеты ядра в нескольких версиях",
  "checkOfficial": "официальный",
  "checkOrderTip": "порядок загрузки бандла сообщества конфликтует с объявленными правилами before/after",
  "checkOrphans": "Неверные записи конфига",
  "checkOrphansEmpty": "Неверных записей нет",
  "checkOverridden": "переопределяет",
  "checkOverrides": "Переопределения",
  "checkOverridesEmpty": "Переопределений нет",
  "checkPatch": "файл патча",
  "checkPeerEmpty": "Расхождений версий зависимостей нет",
  "checkPeerInfo": "{0} записей к сведению (не подтверждено)",
  "checkPeerMismatches": "Расхождения версий зависимостей",
  "checkPeerOverview": "расхождений: {0} · к сведению: {1}",
  "checkProfile": "профиль",
  "checkRange": "объявленный диапазон",
  "checkRefresh": "Проверить заново",
  "checkResolved": "разрешённая версия",
  "checkSatisfied": "удовлетворено",
  "checkSource": "источник",
  "checkUnknown": "неизвестно",
  "checkUnsatisfied": "не удовлетворено",
  "checkWarnings": "Предупреждения",
  "checkWarningsEmpty": "Предупреждений нет",
  "cmdDetails": "Команда установки",
  "confirm": "Подтвердить",
  "confirmRemove": "Подтверждаете?",
  "confirmTitle": "Установка",
  "confirmWarn": "Плагины — сторонний код сообщества. Устанавливая, вы доверяете этому источнику; сборочные скрипты по умолчанию заблокированы.",
  "credsWarning": "Внимание: в копию попадают настройки профиля и файлы, где могут лежать секреты (config.toml, .env и подобные). Локальная выгрузка ничего не вырезает, поэтому выгружайте на WebDAV, которому доверяете.",
  "deprecatedBadge": "Устарел",
  "deprecatedWarn": "Каталог помечает этот плагин как устаревший; новым пользователям ставить его не советуют.",
  "diagExplain": "Что это",
  "diagExplainText": "Эта страница ищет плагины, конфликтующие друг с другом, несовпадения версий зависимостей и неверный порядок загрузки. Термины:",
  "diagOkAll": "Всё в порядке: конфликтов, проблем с зависимостями и порядком не найдено",
  "diagTermBundle": "бандл — один пакет плагина, применяется по порядку",
  "diagTermEntry": "запись — то, что плагин добавляет в работающую композицию",
  "diagTermOrder": "порядок загрузки — очерёдность активации; более поздний может перекрыть более ранний",
  "diagTermOrphan": "неверная запись — конфиг ссылается на то, чего нет",
  "diagTermPeer": "peer-зависимость — пакет, который плагин ждёт от хоста",
  "diagTermShadow": "перекрытие — старая копия из плагина закрывает более новую хостовую",
  "disable": "Выключить",
  "disabledState": "Выключен",
  "dismiss": "Скрыть",
  "dismissNotice": "Скрыть это уведомление",
  "duplicateNames": "Плагины с одинаковыми именами (к сведению, это не конфликт)",
  "empty": "Подходящих плагинов нет",
  "enable": "Включить",
  "envFix": "Настроить автоматически",
  "envFixFail": "Автоматическая настройка не удалась — выгрузите журнал и пришлите нам файл",
  "envFixing": "Настройка…",
  "envMissing": "Перед установкой плагинов нужен один небольшой компонент",
  "exportLog": "Выгрузить журнал",
  "exportLogFail": "Не удалось выгрузить журнал",
  "exportedLog": "Журнал выгружен: dsh-market-log.txt — приложите его к обращению",
  "exportingLog": "Выгрузка…",
  "filter": "Фильтр",
  "filterDir": "Порядок",
  "filterSort": "Поле сортировки",
  "filterTime": "Вышло за",
  "firstPage": "В начало",
  "gist": "GitHub Gist",
  "gistCreated": "Выгружено:",
  "gistErrAuth": "GitHub не авторизовал: токен неверный или истёк, либо gh CLI не залогинен",
  "gistErrInvalid": "Содержимое Gist повреждено или формат копии не поддерживается",
  "gistErrNetwork": "GitHub недоступен — проверьте сеть или прокси",
  "gistErrNoId": "Для обновления нужен идентификатор Gist — заполните поле или переключитесь на «Создать»",
  "gistErrNotFound": "Gist не найден — проверьте идентификатор или ссылку",
  "gistErrRateLimit": "Достигнут лимит GitHub, либо у токена нет права gist",
  "gistErrTimeout": "GitHub не ответил вовремя — проверьте сеть и повторите",
  "gistExport": "Выгрузить в Gist…",
  "gistExportDone": "Выгружено в Gist",
  "gistExportGo": "Выгрузить",
  "gistExportHint": "Отмечено всё — полная копия вместе с настройками; если снять любую галочку, выгрузятся только выбранные плагины, а настройки — по отдельному флажку.",
  "gistExportSelect": "Выберите плагины для выгрузки",
  "gistId": "Идентификатор или ссылка на Gist (при выгрузке оставьте пустым, чтобы создать новый приватный)",
  "gistImport": "Загрузить из Gist",
  "gistIncludeConfig": "Включить файлы настроек (в них могут быть секреты)",
  "gistModeCreate": "Создать новый приватный Gist",
  "gistModeUpdate": "Обновить Gist из поля",
  "gistNoPlugins": "В этом профиле нечего выгружать",
  "gistNote": "В отличие от локальной выгрузки (архив на этой машине), Gist нужен для переноса между машинами: выгрузите в приватный Gist и загрузите на другом компьютере под тем же аккаунтом. Токен живёт только в памяти этой вкладки и никогда не пишется в браузерное хранилище; если залогинен gh CLI или задан DSH_GITHUB_TOKEN, вводить его не нужно. Gist приватный, до 1 МБ на файл.",
  "gistSelectAll": "Выбрать все",
  "gistSelectNone": "Снять выбор",
  "gistSpecLocal": "локально",
  "gistSrcEnv": "переменная DSH_GITHUB_TOKEN",
  "gistSrcGh": "gh CLI",
  "gistSrcToken": "введён вручную",
  "gistToken": "Токен GitHub (только в памяти вкладки — после обновления страницы введите заново; оставьте пустым, чтобы использовать серверный DSH_GITHUB_TOKEN или залогиненный gh CLI)",
  "gistVerify": "Проверить связь",
  "gistVerifySource": "Проверено — источник токена: {0}",
  "gotIt": "Понятно",
  "groupAdd": "Добавить плагин",
  "groupAddEmpty": "Все установленные плагины уже в этой группе",
  "groupAddTheme": "Добавить тему",
  "groupAssign": "Назначить",
  "groupConfirmDelete": "Удалить группу?",
  "groupCreate": "Создать",
  "groupDelete": "Удалить группу",
  "groupEmpty": "Пока пусто",
  "groupMixed": "Включена частично",
  "groupNamePh": "Название группы",
  "groupNew": "Новая группа",
  "groupRemove": "Убрать",
  "groupRename": "Переименовать",
  "hostDependencyMore": "ещё находок пропущено: {0}",
  "hostDependencyWarning": "Плагин перечисляет в зависимостях известные общие пакеты хоста DSH. Это может перекрыть хостовую версию; проверка смотрит только манифест и не подтверждает, что в рантайме появился дубль:",
  "hotBanner": "плагины готовы — обновите страницу, чтобы ими пользоваться",
  "install": "Установить",
  "installFail": "Установить не удалось",
  "installReplacement": "Установить замену",
  "installedBadge": "✓ Установлен",
  "installedEmpty": "Плагинов сообщества пока нет — загляните во вкладку «Обзор»",
  "installing": "Установка…",
  "lastPage": "В конец",
  "linkedDev": "подключён как разработка",
  "loadFail": "Не удалось загрузить каталог плагинов, попробуйте позже",
  "loading": "Загрузка каталога…",
  "localOnly": "Адрес WebDAV и учётные данные остаются только в этом браузере.",
  "marketNoToggle": "Сам маркет выключить нельзя",
  "marketUpdate": "Доступно обновление маркета — обновить",
  "nav": "Маркет плагинов",
  "nextPage": "Дальше",
  "noGroups": "Групп пока нет — создайте",
  "notInstalled": "Не установлен",
  "orderAlreadyOptimal": "Текущий порядок уже удовлетворяет всем правилам и зависимостям — переставлять нечего",
  "orderApplied": "✓ Применено — перезапустите, чтобы вступило в силу",
  "orderApply": "Применить порядок",
  "orderAutoSort": "Отсортировать автоматически",
  "orderConflicts": "конфликты before/after в текущем порядке",
  "orderDiffHint": "Этот порядок изменит композицию: переопределений {0}, потерянных записей {1}, дублей {2}",
  "orderDown": "↓",
  "orderDrag": "Перетащите, чтобы изменить порядок",
  "orderDragHint": "Тяните ⠿, чтобы переставить; «Применить порядок» сохранит",
  "orderReset": "Сбросить черновик",
  "orderSection": "Порядок загрузки",
  "orderSuggestApply": "Применить предложенный порядок",
  "orderSuggestHint": "Предложенный порядок (отсортирован по правилам before/after):",
  "orderTrialFail": "Статическая проверка композиции не прошла: {0}",
  "orderUp": "↑",
  "orphanIdRequired": "нет идентификатора",
  "orphanInsertNotArray": "неверный формат",
  "orphanInsertTargetMissing": "цель не найдена",
  "orphanInsertTargetNotGroup": "цель не является группой",
  "orphanNameMismatch": "имя не совпадает",
  "orphanPatchTargetMissing": "цель не найдена",
  "orphanReasonOther": "другое",
  "packagesDone": "обработано пакетов: {0}",
  "pageInfo": "Страница {0} из {1}",
  "partialNote": "Отменено — часть изменений уже применена",
  "patchDisabled": "Выключен патчем",
  "patchForced": "Включён патчем",
  "perPage": "На странице",
  "phaseBuilding": "Сборочные скрипты",
  "phaseDownloading": "Загрузка",
  "phaseLinking": "Связывание",
  "phaseResolving": "Разрешение зависимостей",
  "prevPage": "Назад",
  "progressHint": "Первая установка скачивает и разрешает зависимости — крупные плагины занимают 1–3 минуты",
  "published": "выпущен",
  "readme": "README",
  "refresh": "Обновить",
  "refreshBanner": "изменения применены — обновите страницу, чтобы их увидеть",
  "replacementHint": "Каталог предлагает",
  "restartBanner": "изменения внесены — перезапустите DeepSeek Harness",
  "restartFail": "Перезапустить не удалось",
  "restartHint": "Как перезапустить: остановите текущий процесс dsh и запустите его снова (например, dsh web)",
  "restartNow": "Перезапустить",
  "restartTimeout": "Не дождались запуска DeepSeek Harness",
  "restarting": "Перезапуск…",
  "restoreConfirm": "Восстановление перезапишет настройки этого профиля и переустановит плагины. Продолжить?",
  "restoreDone": "Восстановление завершено — перезапустите DeepSeek Harness",
  "restoreMissing": "Плагинов из копии не установлено: {0}",
  "restorePartial": "Восстановление продолжилось, но эти плагины установить не удалось:",
  "restorePreviewDone": "Копия загружена. Проверьте вкладку «Установленные» и запускайте восстановление.",
  "restoreStart": "Начать восстановление",
  "searchPh": "Поиск плагинов: уведомления, терминал, память…",
  "setCardDesc": "Версия маркета, обновление и удаление.",
  "setSelfCancel": "Отмена",
  "setSelfConfirm": "Удалить маркет плагинов? Поставить его заново можно будет только из командной строки.",
  "setSelfFailed": "Операция не удалась",
  "setSelfPurge": "Заодно стереть данные маркета",
  "setSelfPurgeOff": "Данные маркета сохранятся. Учтите: плагины, которые он выключил, останутся выключенными, а интерфейса, чтобы вернуть их, после удаления не будет.",
  "setSelfPurgeOn": "Будут удалены: список выключенных плагинов, свои группы и строки выключения, которые маркет записал в патч профиля, — выключенные им плагины снова заработают. Паролей и токенов это не касается: маркет их на диск не пишет.",
  "setSelfRemove": "Удалить маркет плагинов",
  "setSelfRemoveConfirm": "Удалить",
  "setSelfRemoveHint": "Удаляет маркет из этого профиля. Остальные плагины не трогаются.",
  "setSelfRemoved": "Удалён",
  "setSelfRemovedHint": "Перезапустите DeepSeek Harness, чтобы завершить.",
  "setSelfRestartAfter": "Перезапустить DeepSeek Harness сразу после удаления",
  "setSelfRestartingHint": "Перезапуск DeepSeek Harness…",
  "setSelfUpToDate": "Обновлений нет",
  "setSelfUpdate": "Обновить",
  "setSelfUpdateHint": "Обновление скачает новую версию; она заработает после перезапуска.",
  "setSelfUpdateReady": "Доступна новая версия:",
  "setSelfUpdatedHint": "Скачано. Перезапустите DeepSeek Harness, чтобы обновление вступило в силу: страница обновляется сразу, серверная половина — нет.",
  "setSelfWorking": "Удаление…",
  "sortAdded": "Дата выпуска",
  "sortAsc": "По возрастанию",
  "sortDesc": "По убыванию",
  "sortNewest": "Сначала новые",
  "sortOldest": "Сначала старые",
  "sortStars": "Звёзды",
  "stateBroken": "Установлен, но не прошёл проверку",
  "stateDisabled": "Выключен",
  "stateInert": "Установлен, но не является плагином слоя профиля",
  "stateLive": "Работает (загружен на лету)",
  "stateRestart": "Установлен — перезапустите, чтобы применить",
  "subtitle": "Плагины сообщества для DeepSeek Harness",
  "tabBackup": "Копия и восстановление",
  "tabDiagnostics": "Диагностика",
  "tabDiscover": "Обзор",
  "tabGroups": "Группы",
  "tabInstalled": "Установленные",
  "tabList": "Список",
  "tabThemes": "Темы",
  "terminalWarn": "Похоже, это плагин для терминала: в веб-профиле он может ничего не делать или даже сломать запуск DeepSeek Harness. Прочитайте его README и ставьте в тот профиль, для которого он написан.",
  "themeActive": "Активна",
  "themeApply": "Применить",
  "themeDeactivate": "Отключить",
  "themeEmpty": "Других тем в каталоге пока нет — следите за обновлениями",
  "timeAll": "Всё время",
  "timeDay": "Сутки",
  "timeMonth": "30 дней",
  "timeQuarter": "90 дней",
  "timeWeek": "7 дней",
  "timeYear": "Год",
  "toastReady": "установлен и работает",
  "toastTheme": "теперь активна. Переключить можно в «Настройки → Маркет плагинов → Темы»",
  "toggleFail": "Переключить не удалось",
  "ungrouped": "Без группы",
  "uninstall": "Удалить",
  "uninstallConfirmDesc": "Плагин будет удалён из текущего профиля.",
  "uninstalling": "Удаление…",
  "upToDate": "Обновлений нет",
  "update": "Обновить",
  "updateAll": "Обновить все",
  "updateFail": "Обновить не удалось",
  "updateNow": "Обновить сейчас",
  "updated": "✓ Обновлён — перезапустите, чтобы применить",
  "updatedLive": "✓ Обновлён — работает",
  "updating": "Обновление…",
  "versionHint": "Версия маркета плагинов — указывайте её при обращении",
  "viewReplacement": "Посмотреть замену",
  "viewSource": "Исходник",
  "webdav": "WebDAV",
  "webdavNote": "Адрес WebDAV и имя пользователя остаются только в этом браузере; пароль хранится на сервере и вводится заново каждую сессию.",
  "webdavPassword": "Пароль (необязательно)",
  "webdavPreset": "Готовая настройка провайдера",
  "webdavRestore": "Восстановить с WebDAV",
  "webdavUpload": "Выгрузить копию",
  "webdavUrl": "Адрес файла копии",
  "webdavUser": "Имя пользователя (необязательно)"
 },
 "feedback": {
  "action.dislike": "Плохой ответ",
  "action.dislikeActive": "Убрать оценку",
  "action.like": "Хороший ответ",
  "action.likeActive": "Убрать оценку",
  "error.conflict": "Эту оценку изменили в другом месте; показано актуальное состояние",
  "error.generic": "Не удалось сохранить оценку",
  "error.load": "Не удалось загрузить оценку",
  "note.aria": "Комментарий к оценке",
  "note.cancel": "Отмена",
  "note.dialog": "Отзыв",
  "note.open": "Добавить комментарий",
  "note.placeholder": "Что получилось хорошо, а что нет? (необязательно)",
  "note.save": "Сохранить"
 },
 "goal": {
  "action.cancel": "Отменить правку",
  "action.clear": "Снять цель",
  "action.edit": "Изменить цель",
  "action.pause": "Приостановить цель",
  "action.resume": "Продолжить цель",
  "action.save": "Сохранить цель",
  "commandInput.aria": "Ввод команды",
  "objective.aria": "Формулировка цели",
  "phase.active": "Цель в работе",
  "phase.blocked": "Цель заблокирована",
  "phase.paused": "Цель на паузе"
 },
 "im-hub": {
  "f.agentCwd": "Рабочая папка",
  "f.agentCwdHint": "Папка для сессий агента; пусто — папка процесса dsh.",
  "f.agentMaxMessageLength": "Длина сообщения",
  "f.agentMaxMessageLengthHint": "Максимум символов в исходящем сообщении; длинные ответы разбиваются.",
  "f.agentModel": "Модель",
  "f.agentModelHint": "Переопределить модель; пусто — как задано в установке.",
  "f.agentProvider": "Провайдер",
  "f.agentProviderHint": "Переопределить провайдера модели; пусто — как задано в установке.",
  "f.allowedUserIdsHint": "Идентификаторы через запятую; пусто — доступ всем (для боевой работы не советуем).",
  "f.configured": "Задано",
  "f.enabled": "Включено",
  "f.enabledHint": "Общий выключатель всего IM-шлюза.",
  "f.feishuAllowedUserIds": "Разрешённые open id",
  "f.feishuAppId": "App id",
  "f.feishuAppIdHint": "App id приложения Feishu (cli_…).",
  "f.feishuAppSecret": "App secret",
  "f.feishuEnabled": "Включено",
  "f.feishuEnabledHint": "Включить адаптер Feishu по постоянному WebSocket-соединению (публичный адрес не нужен).",
  "f.httpHost": "Адрес привязки",
  "f.httpHostHint": "Адрес, на котором слушают HTTP-серверы в режиме вебхуков.",
  "f.httpPort": "Порт привязки",
  "f.httpPortHint": "Порт, на котором слушают HTTP-серверы в режиме вебхуков.",
  "f.inherit": "Наследовать",
  "f.larkAllowedUserIds": "Разрешённые open id",
  "f.larkAppId": "App id",
  "f.larkAppSecret": "App secret",
  "f.larkEnabled": "Включено",
  "f.larkEnabledHint": "Включить международный адаптер Lark (open.larksuite.com).",
  "f.mockEnabled": "Включено",
  "f.mockEnabledHint": "Адаптер только для тестов: локальный HTTP-эндпоинт без учётных данных платформы.",
  "f.mockPort": "Порт",
  "f.mockPortHint": "Фиксированный HTTP-порт тестового эндпоинта (0 — любой свободный).",
  "f.notConfigured": "Не задано",
  "f.off": "Выкл",
  "f.on": "Вкл",
  "f.secretHint": "Хранится на сервере и больше не показывается. Оставьте пустым, чтобы сохранить текущее значение.",
  "f.telegramAllowedUserIds": "Разрешённые id пользователей",
  "f.telegramEnabled": "Включено",
  "f.telegramEnabledHint": "Включить адаптер Telegram Bot API с опросом обновлений.",
  "f.telegramToken": "Токен бота",
  "f.telegramTokenHint": "Токен от @BotFather (123456:ABC-DEF…).",
  "f.wecomAgentId": "Agent id",
  "f.wecomAgentIdHint": "Agent id приложения WeCom.",
  "f.wecomAllowedUserIds": "Разрешённые id пользователей",
  "f.wecomCorpId": "Corp id",
  "f.wecomCorpIdHint": "Идентификатор организации из консоли WeCom.",
  "f.wecomCorpSecret": "App secret",
  "f.wecomEnabled": "Включено",
  "f.wecomEnabledHint": "Включить адаптер WeCom с обратным вызовом (нужен публичный адрес).",
  "f.wecomEncodingAesKey": "EncodingAESKey",
  "f.wecomToken": "Токен обратного вызова",
  "g.agent": "Агент",
  "g.feishu": "Feishu (Китай)",
  "g.general": "Общие",
  "g.http": "HTTP (режим вебхуков)",
  "g.lark": "Lark (международный)",
  "g.mock": "Тестовый адаптер",
  "g.telegram": "Telegram",
  "g.wecom": "WeCom (WeChat Work)",
  "p.agentCwd": "Например: /home/user/projects/my-agent (пусто — папка DSH)",
  "p.agentMaxMessageLength": "Например: 4000",
  "p.agentModel": "Например: deepseek-v4-flash (пусто — по умолчанию)",
  "p.agentProvider": "Например: volcengine (пусто — по умолчанию)",
  "p.feishuAllowedUserIds": "Например: ou_xxxxxxxxxxxxx",
  "p.feishuAppId": "Например: cli_xxxxxxxxxxxxx",
  "p.feishuAppSecret": "App Secret приложения Feishu",
  "p.httpHost": "Например: 0.0.0.0",
  "p.httpPort": "Например: 8080",
  "p.larkAllowedUserIds": "Например: ou_xxxxxxxxxxxxx",
  "p.larkAppId": "Например: cli_xxxxxxxxxxxxx",
  "p.larkAppSecret": "App Secret приложения Lark",
  "p.mockPort": "Например: 9099 (0 — автоматически)",
  "p.telegramAllowedUserIds": "Например: 123456789, 987654321",
  "p.telegramToken": "Например: 123456789:AA...",
  "p.wecomAgentId": "Например: 1000002",
  "p.wecomAllowedUserIds": "Например: ivanov, petrov",
  "p.wecomCorpId": "Например: wwxxxxxxxxxxxxxx",
  "p.wecomCorpSecret": "Secret приложения WeCom",
  "p.wecomEncodingAesKey": "EncodingAESKey из 43 символов",
  "p.wecomToken": "Токен адреса обратного вызова",
  "settings.collapse": "Свернуть",
  "settings.description": "Подключает агентов dsh к Feishu (Lark), WeCom и Telegram. Каждый чат получает свою сессию агента.",
  "settings.discard": "Отменить",
  "settings.expand": "Развернуть",
  "settings.invalidNumber": "Введите корректное число",
  "settings.overridden": "Переопределено",
  "settings.readOnly": "Установка доступна только для чтения: настройки из интерфейса не меняются.",
  "settings.reset": "Сбросить",
  "settings.save": "Сохранить",
  "settings.saveFailed": "Сохранить не удалось",
  "settings.saving": "Сохранение…",
  "settings.title": "IM-шлюз (dsh-im-hub)",
  "settings.unsaved": "Есть несохранённые изменения"
 },
 "job": {
  "count.idle.one": "{count} фоновая задача",
  "count.idle.other": "{count} фоновых задач",
  "count.live.one": "{count} фоновая задача выполняется",
  "count.live.other": "{count} фоновых задач выполняется",
  "duration.hours": "{hours} ч {minutes} мин",
  "duration.minutes": "{minutes} мин {seconds} с",
  "duration.seconds": "{seconds} с",
  "duration.title.done": "Заняло {duration}",
  "duration.title.live": "Выполняется {duration}",
  "list.aria": "Фоновые задачи",
  "status.completed": "завершена",
  "status.failed": "ошибка",
  "status.killed": "отменена",
  "status.running": "выполняется",
  "status.stopping": "останавливается"
 },
 "model": {
  "action.reload": "Обновить",
  "blocked.composer": "Эта модель недоступна — выберите другую, чтобы продолжить",
  "command.description": "Выбрать модель для этого диалога",
  "effort.providerDefault": "По умолчанию",
  "empty.efforts": "У этой модели нет уровней рассуждения.",
  "empty.models": "Доступных моделей нет.",
  "error.action": "Операция с моделью не удалась: {message}",
  "menu.aria": "Модель и уровень рассуждения",
  "menu.effort": "Уровень рассуждений",
  "menu.model": "Модель",
  "option.loadError": "Каталог не загрузился: {message}",
  "status.loading": "Обновление списка моделей…",
  "trigger.aria": "Выбор модели, сейчас {model}",
  "trigger.ariaEffort": "Выбор модели, сейчас {model}, уровень рассуждения {effort}",
  "trigger.fallback": "Выбрать модель",
  "trigger.selectAria": "Выбрать модель",
  "warning.groupLoad": "{name} не загрузился: {message}"
 },
 "permission.access": {
  "confirm.acknowledge": "Я понимаю риски и хочу продолжить",
  "confirm.cancel": "Отмена",
  "confirm.description": "Полный доступ убирает часть подтверждений и позволяет агенту действовать напрямую, включая чувствительные операции, изменение файлов и внешние команды. Включайте, только если доверяете текущей задаче.",
  "confirm.enable": "Включить полный доступ",
  "confirm.title": "Включить полный доступ?"
 },
 "pin": {
  "action.pin": "Закрепить",
  "action.unpin": "Открепить"
 },
 "plan": {
  "chip.off.aria": "Режим плана выключен, нажмите, чтобы включить",
  "chip.off.title": "Режим плана выключен — нажмите, чтобы включить (/plan)",
  "chip.on.aria": "Режим плана включён, нажмите, чтобы выключить",
  "chip.on.title": "Режим плана включён — нажмите, чтобы выключить (/plan off)"
 },
 "plugin-store": {
  "dialog.close": "Закрыть магазин плагинов",
  "header.open": "Открыть магазин плагинов",
  "header.title": "Магазин плагинов DSH",
  "settings.tab": "Магазин плагинов",
  "store.analyzeFailed": "Передать разбор агенту не удалось",
  "store.analyzeHint": "Отправить эту ошибку в новую сессию агента для разбора.",
  "store.analyzeSent": "Отправлено агенту",
  "store.analyzeWithAgent": "Попросить агента разобраться",
  "store.analyzing": "Создаём сессию агента…",
  "store.cancel": "Отмена",
  "store.category": "Категория",
  "store.categoryAll": "Все категории",
  "store.confirmInstall": "Установить плагин",
  "store.confirmRemove": "Удалить плагин",
  "store.confirmUpdate": "Обновить плагин",
  "store.copied": "Ссылка для установки скопирована",
  "store.copyInstall": "Скопировать ссылку для установки",
  "store.disclaimer": "Наличие в каталоге не подтверждает работоспособность, совместимость, безопасность или качество.",
  "store.done": "Готово",
  "store.empty": "Под эти фильтры ничего не подходит",
  "store.install": "Установить",
  "store.installFailed": "Установить не удалось",
  "store.installSuccess": "Установлено. Перезапустите DSH Web, чтобы плагин заработал.",
  "store.installed": "Установлен",
  "store.installedLoadFailed": "Список установленных плагинов недоступен",
  "store.installedOnly": "Только установленные",
  "store.installing": "Установка…",
  "store.loadFailed": "Не удалось загрузить каталог",
  "store.loadMore": "Показать ещё",
  "store.loading": "Загрузка каталога плагинов…",
  "store.openDetails": "Открыть карточку в магазине",
  "store.refresh": "Обновить каталог",
  "store.refreshFailed": "Каталог не обновился; показаны последние успешные данные",
  "store.remove": "Удалить плагин",
  "store.removeDetail": "Меняется только зависимость текущего профиля. Чтобы удаление вступило в силу, перезапустите DSH Web.",
  "store.removeFailed": "Удалить не удалось",
  "store.removeLead": "Плагин будет удалён из текущего профиля DSH Web.",
  "store.removeSuccess": "Удалено. Перезапустите DSH Web, чтобы изменение вступило в силу.",
  "store.removeTitle": "Удаление плагина",
  "store.removing": "Удаление…",
  "store.results": "{visible} из {total} проектов",
  "store.retry": "Повторить",
  "store.riskAcknowledge": "Я понимаю риск и хочу установить этот сторонний плагин",
  "store.riskDetail": "Присутствие в каталоге не является проверкой безопасности, совместимости или качества. Установленный код выполняется с правами процесса DSH, а чтобы он заработал, DSH Web нужно перезапустить.",
  "store.riskLead": "В текущий профиль DSH Web будет установлен код из стороннего репозитория.",
  "store.riskTitle": "Подтверждение риска стороннего плагина",
  "store.search": "Поиск по названию, автору, описанию или теме",
  "store.sort": "Сортировка",
  "store.sortName": "Название",
  "store.sortRecommended": "Рекомендуемые",
  "store.sortStars": "Звёзды",
  "store.sortUpdated": "Недавно обновлённые",
  "store.stars": "звёзд: {count}",
  "store.topicListed": "Указана тема",
  "store.update": "Обновить",
  "store.updateAvailable": "Есть обновление",
  "store.updateRiskDetail": "Обновление заменит версию плагина в этом профиле. Чтобы оно вступило в силу, перезапустите DSH Web.",
  "store.updateRiskLead": "В текущий профиль DSH Web будет установлена более новая ревизия стороннего репозитория.",
  "store.updateRiskTitle": "Подтверждение обновления стороннего плагина",
  "store.updateSuccess": "Обновлено. Перезапустите DSH Web, чтобы плагин заработал.",
  "store.updated": "Каталог обновлён {date}",
  "store.updating": "Обновление…",
  "store.validation.check-failed": "Проверка структуры не пройдена",
  "store.validation.check-pending": "Проверка структуры в очереди",
  "store.validation.check-running": "Идёт проверка структуры",
  "store.validation.expired": "Нужна повторная проверка",
  "store.validation.inconclusive": "Требует рассмотрения",
  "store.validation.not-applicable": "Вне проверки плагинов",
  "store.validation.recorded": "Есть запись о проверке",
  "store.validation.sandbox-failed": "Проверка в песочнице не пройдена",
  "store.validation.sandbox-pending": "Проверка в песочнице в очереди",
  "store.validation.sandbox-running": "Идёт проверка в песочнице",
  "store.validation.security-review": "Проверка безопасности",
  "store.validation.unrecognized": "Требует опознания",
  "store.validation.verified": "Проверен",
  "store.verified": "Проверен",
  "store.verifiedOnly": "Только проверенные"
 },
 "question": {
  "action.next": "Дальше",
  "action.skip": "Пропустить вопрос",
  "custom.placeholder": "Впишите свой ответ",
  "error.incomplete": "Сначала ответьте на этот вопрос.",
  "error.unanswered": "Выберите вариант или впишите свой ответ.",
  "nav.cancel": "Закрыть все вопросы",
  "nav.maximize": "Развернуть карточку вопроса",
  "nav.minimize": "Свернуть карточку вопроса",
  "nav.next": "Следующий вопрос",
  "nav.prev": "Предыдущий вопрос",
  "option.recommended": "Рекомендуем",
  "plan.approve": "Утвердить",
  "plan.decline": "Отклонить",
  "plan.discuss": "Обсудить",
  "plan.header": "Проверка плана"
 },
 "reference": {
  "candidate.file": "Файл",
  "candidate.folder": "Папка",
  "candidate.noCwd": "(нет cwd)",
  "candidate.session": "Сессия",
  "section.files": "Файлы и папки",
  "section.sessions": "Диалоги сессий"
 },
 "session-log-download": {
  "dialog.close": "Закрыть",
  "dialog.commandFailed": "Не удалось запустить экспорт сессии.",
  "dialog.errorTitle": "Экспорт сессии не удался",
  "dialog.preparingDescription": "Готовится ZIP с этой сессией, её подсессиями и вложениями.",
  "dialog.preparingTitle": "Экспорт сессии",
  "dialog.successDescription": "Браузер загружает ZIP с сессией.",
  "dialog.successTitle": "Загрузка сессии началась"
 },
 "settings": {
  "close": "Закрыть",
  "general.nav": "Общие",
  "openDocument": "Открыть файл настроек",
  "openDocument.error": "Не удалось открыть файл настроек",
  "title": "Настройки",
  "trigger": "Настройки"
 },
 "settings.agentPreset": {
  "brokenBadge": "Не загрузился",
  "brokenNoCopy": "Пресет, который не загрузился, скопировать нельзя",
  "builtIn": "Встроенный",
  "builtInGroup": "Встроенные",
  "cancel": "Отмена",
  "close": "Закрыть",
  "composition": "Композиция (agent.cordis.yml)",
  "copyIntro": "Пресет копируется целиком на этой машине. Идентификатор станет именем каталога и позже не меняется; всё остальное правится в файлах самого пресета.",
  "copyOf": "Скопирован с",
  "copyTitle": "Скопировать пресет",
  "create": "Создать",
  "creating": "Создание…",
  "creatorDraft": "Набросать свой пресет в режиме «Конструктор»",
  "customGroup": "Свои",
  "delete": "Удалить",
  "deleteConfirm": "Удалить",
  "deleteDescription": "Каталог пресета будет удалён. Уже запущенные на нём сессии продолжат работать, но выбрать его для новых нельзя.",
  "deleteTitle": "Удалить этот пресет?",
  "deleting": "Удаление…",
  "description": "Действует на сессии, запущенные с этого момента. Работающие сессии остаются на своём пресете.",
  "displayName": "Название",
  "displayNamePlaceholder": "Показывается в списке; по умолчанию — идентификатор",
  "duplicate": "Скопировать",
  "duplicateUnavailable": "В этой установке нет каталога пресетов с правом записи",
  "error": "Не удалось загрузить пресеты агента.",
  "headerHint": "Пресет агента, на котором идёт сессия; зафиксирован при запуске",
  "idInvalid": "Строчные буквы, цифры и дефисы, начиная с буквы или цифры.",
  "idRequired": "Задайте пресету идентификатор.",
  "idTaken": "Пресет с таким идентификатором уже есть.",
  "inUse": "Используется",
  "loading": "Загрузка пресетов…",
  "nav": "Пресеты агента",
  "noDescription": "Без описания.",
  "openLocation": "Открыть папку",
  "presetCodeDescription": "Всё, что умеет обычный режим, но инструменты отдаются через Code Mode SDK: модель собирает многошаговые операции в одну программу на TypeScript.",
  "presetCodeName": "Режим кода",
  "presetCordisDescription": "Для создания своих пресетов: всё из обычного режима плюс инспекция рантайма, опыты с плагинами и подсказки по авторству пресетов.",
  "presetCordisName": "Конструктор",
  "presetId": "Идентификатор",
  "presetIdPlaceholder": "my-agent",
  "presetMinimalDescription": "Агент из двух инструментов: постоянный bash и str_replace_editor.",
  "presetMinimalName": "Минимальный режим",
  "presetStandardDescription": "Полноценный кодинг-агент: правка файлов, консоль, поиск по файлам и в вебе, скиллы, планирование, цели, субагенты и воркфлоу.",
  "presetStandardName": "Обычный режим",
  "retry": "Повторить",
  "revealedPathLabel": "Файлы пресета:",
  "seatHint": "Пресет агента для сессии, которую вы собираетесь запустить",
  "sectionIntro": "Пресет — это состав плагинов, на котором работает агент сессии: его инструменты, промпт и возможности. Скопируйте готовый и допилите под себя или попросите агента набросать свой в режиме «Конструктор».",
  "setDefault": "Сделать основным",
  "showLocation": "Показать расположение",
  "title": "Пресет агента",
  "userTrust": "Свой",
  "view": "Посмотреть"
 },
 "settings.locale": {
  "language.title": "Язык"
 },
 "settings.models": {
  "add": "Добавить провайдера",
  "addModel": "Добавить модель",
  "advancedHint": "Остальные поля живут в settings.yaml — правьте этот раздел напрямую.",
  "apply": "Применить",
  "applying": "Применение…",
  "baseUrl": "Базовый URL",
  "baseUrlDefault": "По умолчанию у провайдера",
  "cancel": "Отмена",
  "close": "Закрыть",
  "conflict": "Пока карточка была открыта, настройки изменил кто-то ещё. Закройте и откройте заново, чтобы править актуальные значения.",
  "contextWindow": "Окно контекста",
  "contextWindowPlaceholder": "Как у провайдера по умолчанию",
  "create": "Создать провайдера",
  "creating": "Создание…",
  "credentialConfigured": "API-ключ задан",
  "credentialMissing": "API-ключ не задан",
  "customAdd": "Добавить своего провайдера",
  "customApi": "Протокол API",
  "customApiUnset": "Не выбран",
  "customDisplayName": "Отображаемое имя",
  "customNeedsBaseUrl": "Своему провайдеру нужен базовый URL.",
  "customNeedsModels": "Своему провайдеру нужна хотя бы одна модель.",
  "customRoute": "Идентификатор провайдера",
  "customRouteHint": "Идентификатор в нижнем регистре, начинается с буквы. По нему провайдер адресуется в запросах, и так же называется его ключ.",
  "customRouteInvalid": "Начните со строчной буквы, дальше строчные буквы, цифры и дефисы.",
  "customRouteTaken": "Такой идентификатор уже занят другим провайдером.",
  "customTag": "Свой",
  "customTitle": "Свой провайдер",
  "customized": "Настройки изменены",
  "deleteConfirm": "Удалить {provider}",
  "deleteDescription": "Удаление {provider} убирает его настройки. Ключ, которым он пользовался, хранится отдельно и останется.",
  "deleteDescriptionWithCredential": "Удаление {provider} убирает его настройки и сохранённый API-ключ.",
  "deleteTitle": "Удалить {provider}?",
  "deleting": "Удаление {provider}…",
  "edit": "Изменить",
  "editProvider": "Изменить {provider}",
  "fetchAdopt": "Добавить выбранные",
  "fetchDescription": "Вот модели, доступные у этого провайдера. Отметьте те, что нужно добавить.",
  "fetchDeselectAll": "Снять выбор",
  "fetchEmpty": "Провайдер не вернул ни одной модели. Добавьте их вручную.",
  "fetchModels": "Запросить список моделей",
  "fetchNeedsBaseUrl": "Сначала укажите базовый URL, потом запрашивайте.",
  "fetchSelectAll": "Выбрать все",
  "fetchTitle": "Выберите модели",
  "fetching": "Запрос к провайдеру…",
  "intro": "Введите свои API-ключи, чтобы пользоваться моделями этих провайдеров.",
  "keyBlank": "Введите API-ключ или оставьте поле пустым, чтобы сохранить прежний.",
  "keyBlankNew": "Введите API-ключ или оставьте поле пустым, если провайдер авторизуется иначе.",
  "keyEnvLocked": "Задан переменной окружения (только чтение)",
  "keyIllegalCharacters": "Ключ в недопустимом формате. Проверьте его.",
  "keyInput": "API-ключ",
  "keyPlaceholder": "Введите API-ключ",
  "keyPlaceholderNative": "Введите API-ключ или оставьте пустым для авторизации из окружения",
  "keyRequired": "Чтобы продолжить, введите API-ключ.",
  "keyStored": "Задан — введите новое значение, чтобы заменить",
  "loadFailed": "Не удалось загрузить список провайдеров",
  "maxTokens": "Максимум выходных токенов",
  "maxTokensPlaceholder": "Как у провайдера по умолчанию",
  "model": "Модель",
  "modelAdvanced": "Ёмкости",
  "modelCapacityInvalid": "Ёмкость задаётся числом, можно с суффиксом K или M.",
  "modelContextInvalid": "Окно контекста — положительное число, например 131072, 256K или 1M.",
  "modelContextWindow": "Окно контекста",
  "modelDuplicate": "Каждый идентификатор модели встречается один раз.",
  "modelId": "Идентификатор модели",
  "modelIdDuplicate": "Идентификатор модели должен быть уникальным.",
  "modelIdRequired": "Нужен идентификатор модели.",
  "modelMaxTokens": "Максимум выходных токенов",
  "modelMaxTokensInvalid": "Максимум выходных токенов — положительное число, например 8192, 64K или 1M.",
  "modelName": "Отображаемое имя",
  "modelNameInvalid": "Отображаемое имя не может быть пустым.",
  "modelNamePlaceholder": "Пусто — возьмётся идентификатор модели",
  "models": "Модели",
  "modelsCustomized": "Каталог моделей изменён",
  "modelsEmpty": "В выборе моделей не будет ничего. Неуказанные идентификаторы всё равно можно отправлять напрямую.",
  "modelsInherited": "По умолчанию, как в адаптере",
  "nav": "Модели",
  "onboardingDescription": "Настройте официального провайдера DeepSeek, чтобы начать.",
  "onboardingLater": "Настроить позже",
  "onboardingSave": "Сохранить и продолжить",
  "onboardingSaving": "Сохранение…",
  "onboardingTitle": "Добавьте API-ключ, чтобы начать",
  "provider": "Провайдер",
  "readOnly": "В этой установке файл настроек доступен только для чтения.",
  "remove": "Удалить",
  "removeModel": "Удалить модель",
  "removeProvider": "Удалить {provider}",
  "resetModels": "Вернуть значения по умолчанию",
  "retry": "Повторить",
  "savedProvider": "{provider} сохранён.",
  "title": "Модели",
  "welcomeError": "Не удалось сохранить подтверждение. Попробуйте ещё раз."
 },
 "settings.permission": {
  "confirm.acknowledge": "Я понимаю риски и хочу продолжить",
  "confirm.cancel": "Отмена",
  "confirm.description": "Полный доступ позволяет новым сессиям реже спрашивать подтверждение и действовать напрямую, включая чувствительные операции, изменение файлов и внешние команды. Включайте, только если доверяете будущим задачам.",
  "confirm.enable": "Включить полный доступ",
  "confirm.title": "Включить полный доступ?",
  "description": "Режим разрешений по умолчанию для новых сессий",
  "loading": "Загрузка",
  "title": "Разрешения",
  "unavailable": "Недоступно"
 },
 "settings.pluginInventory": {
  "active": "Подключён",
  "catalog": "Список плагинов",
  "configuration": "Настройки",
  "cordis": "Состояние Cordis",
  "disabledTag": "Выключен",
  "empty": "Плагинов нет.",
  "emptySearch": "Подходящих плагинов нет.",
  "enabledTag": "Включён",
  "error": "Плагины временно недоступны.",
  "failed": "Не удалось подключить",
  "loading": "Чтение плагинов…",
  "loadingPhase": "Загрузка",
  "pending": "Ожидает зависимости",
  "retry": "Повторить",
  "search": "Поиск плагинов",
  "tab": "Список плагинов",
  "unloading": "Выгружается",
  "unobserved": "Не подключён"
 },
 "settings.plugins": {
  "agentLoopDescription": "Как агент раздаёт вызовы инструментов.",
  "agentLoopMaxParallel": "Параллельных вызовов",
  "agentLoopMaxParallelHint": "Сколько безопасных для параллели вызовов идёт одновременно в пределах шага.",
  "agentLoopTitle": "Цикл агента",
  "bashDescription": "Ограничения для каждой команды, которую запускает агент.",
  "bashMaxOutputBytes": "Предел вывода на поток (байт)",
  "bashMaxOutputBytesHint": "Всё сверх предела уходит во временный файл, а не теряется.",
  "bashTimeoutMs": "Таймаут команды (мс)",
  "bashTimeoutMsHint": "Сколько команда может выполняться до принудительного завершения.",
  "bashTitle": "Консоль",
  "collapse": "Скрыть настройки",
  "configurableTab": "Настройки плагинов",
  "discard": "Отменить",
  "empty": "В этой установке настройки плагинов не выведены.",
  "expand": "Показать настройки",
  "intro": "Настройка и просмотр плагинов, установленных в этой сборке.",
  "invalidNumber": "Введите число или оставьте пустым, чтобы взять значение по умолчанию.",
  "nav": "Плагины",
  "overridden": "Переопределено",
  "readOnly": "В этой установке настройки доступны только для чтения.",
  "reset": "Вернуть по умолчанию",
  "save": "Сохранить",
  "saveFailed": "Установка не приняла эти значения; они оставлены, чтобы вы их поправили.",
  "saving": "Сохранение…",
  "tabs": "Разделы плагинов",
  "title": "Плагины",
  "unsaved": "Не сохранено",
  "webSearchApiKey": "API-ключ",
  "webSearchApiKeyHint": "Хранится вне файла настроек. Оставьте пустым, чтобы сохранить текущий ключ.",
  "webSearchApiKeySet": "Ключ задан.",
  "webSearchApiKeyUnset": "Ключ не задан; без него поиск недоступен.",
  "webSearchBaseUrl": "Адрес сервиса",
  "webSearchBaseUrlHint": "Оставьте пустым, чтобы взять адрес провайдера по умолчанию.",
  "webSearchDescription": "Поисковый провайдер DeepSeek.",
  "webSearchMaxUses": "Максимум поисков на запрос",
  "webSearchMaxUsesHint": "Сколько раз в рамках одного запроса можно искать, прежде чем придётся отвечать.",
  "webSearchTitle": "Поиск в вебе"
 },
 "settings.subscriptions": {
  "cancel": "Отмена",
  "checking": "Проверка…",
  "generating": "Генерация изображения…",
  "image": "изображение",
  "imageClose": "Закрыть",
  "imageLoadFailed": "Повторить",
  "imageLoading": "Загрузка…",
  "imagePreview": "Просмотр изображения",
  "intro": "Вход и выход из провайдеров по подписке. Вход открывает страницу авторизации в новой вкладке; без браузера можно вставить адрес обратного вызова или код.",
  "loggedIn": "Выполнен вход",
  "loggedInAccount": "Вход выполнен как {account}",
  "loggedInAccountExpires": "Вход выполнен как {account} · истекает {date}",
  "loggedInExpires": "Вход выполнен · истекает {date}",
  "login": "Войти",
  "loginInProgress": "Идёт вход…",
  "loginMissingUrl": "ответ на вход пришёл без authorizeUrl",
  "logout": "Выйти",
  "logoutConfirm": "Выйти из {provider}?",
  "manualPlaceholder": "Вставьте адрес обратного вызова или код",
  "manualSummary": "Не работает вход через браузер? Вставьте адрес обратного вызова или код",
  "nav": "Подписки",
  "notLoggedIn": "Вход не выполнен",
  "submit": "Отправить",
  "unavailable": "Нет связи; состояние подписок не загрузить.",
  "usageEmpty": "Окна расхода не переданы.",
  "usageError": "Не удалось получить расход: {message}",
  "usageLoading": "Загрузка расхода…",
  "usagePlan": "Тариф: {plan}",
  "usageRefresh": "Обновить",
  "usageResets": "сбрасывается {date}",
  "usageSession": "Окно 5 часов",
  "usageTitle": "Расход",
  "usageWeekly": "За неделю",
  "usageWindow": "Окно",
  "viewImage": "Посмотреть изображение",
  "viewImageNamed": "Посмотреть {name}"
 },
 "settings.theme": {
  "appearance.dark": "Тёмная",
  "appearance.light": "Светлая",
  "appearance.system": "Как в системе",
  "appearance.title": "Оформление"
 },
 "sidebar": {
  "session.new": "Новая сессия",
  "session.new.label": "Новая сессия",
  "toggle.collapse": "Свернуть панель",
  "toggle.open": "Открыть панель"
 },
 "skill": {
  "menu.userOnly": "только вручную",
  "row.failed": "Не удалось загрузить скилл",
  "row.instructions": "Инструкции",
  "row.running": "Загрузка скилла",
  "row.stopped": "Загрузка скилла остановлена"
 },
 "slash.menu": {
  "command": "Команды",
  "loading": "Загрузка…",
  "skill": "Скиллы",
  "subagent": "Субагенты",
  "suggestions.aria": "Подсказки по вводу"
 },
 "subagent": {
  "activity.inactive": "не работает",
  "activity.running": "работает",
  "branch.collapse": "Свернуть потомков {label}",
  "branch.expand": "Развернуть потомков {label}",
  "count.running.one": "{count} субагент работает",
  "count.running.other": "{count} субагентов работает",
  "count.total.one": "{count} субагент",
  "count.total.other": "{count} субагентов",
  "diagnostic.corrupt": "запись сессии повреждена",
  "diagnostic.unavailable": "запись сессии временно недоступна",
  "diagnostic.unsupported": "неподдерживаемая версия записи субагента",
  "duration.days": "{days} дн",
  "duration.daysHours": "{days} дн {hours} ч",
  "duration.exactDays": "{days} дн {hours} ч {minutes} мин {seconds} с",
  "duration.exactTitle": "Всего активного времени: {duration}",
  "duration.hours": "{hours} ч {minutes} мин {seconds} с",
  "duration.minutes": "{minutes} мин {seconds} с",
  "duration.months": "~{months} мес",
  "duration.monthsDays": "~{months} мес {days} дн",
  "duration.seconds": "{seconds} с",
  "duration.years": "~{years} г",
  "duration.yearsMonths": "~{years} г {months} мес",
  "load.error": "Не удалось загрузить субагентов",
  "loading.aria": "Загрузка субагентов",
  "loading.label": "Загрузка субагентов…",
  "mode.continuable": "с продолжением",
  "mode.oneShot": "разовый",
  "readonly.body": "Родительская сессия офлайн; откройте её заново, чтобы продолжить переписку.",
  "readonly.oneShot.body": "Разовые задачи не принимают продолжения; здесь можно изучить полную запись выполнения.",
  "readonly.oneShot.title": "Запись разового субагента",
  "readonly.title": "Пока этот субагент доступен только для чтения",
  "retry": "Повторить",
  "switcher.aria": "Переключить субагента: {title}",
  "tree.aria": "Сессии субагентов"
 },
 "task-board": {
  "archive.empty": "В архиве пусто",
  "board.archive": "Архив",
  "board.archiveView": "Архив ({count})",
  "board.backToBoard": "К доске",
  "board.close": "В чат",
  "board.created": "Создана",
  "board.empty": "В этой колонке задач нет",
  "board.filterAll": "Все",
  "board.hostError": "Действие на хосте не удалось: {error}",
  "board.hostMeta": "Часовой пояс хоста {timeZone} · ревизия {revision}",
  "board.new": "Новая задача",
  "board.pending": "Отправка",
  "board.retryHost": "Переподключиться к хосту",
  "board.runs": "запусков",
  "board.search": "Фильтр задач…",
  "board.status": "Статус",
  "board.status.backlog": "Бэклог",
  "board.status.done": "Готово",
  "board.status.failed": "Ошибка",
  "board.status.running": "В работе",
  "board.status.todo": "К выполнению",
  "board.title": "Доска задач",
  "board.updated": "Обновлена",
  "card.scheduled": "по расписанию",
  "delete.cancel": "Отмена",
  "delete.confirm": "Удалить «{name}»? Отменить это будет нельзя.",
  "delete.ok": "Удалить",
  "delete.title": "Удаление задачи",
  "detail.archive": "В архив",
  "detail.archivedAt": "В архиве · {time}",
  "detail.close": "Закрыть",
  "detail.delete": "Удалить",
  "detail.description": "Описание",
  "detail.execution": "История запусков",
  "detail.executionEnded": "Завершён",
  "detail.executionSettings": "Параметры запуска",
  "detail.executionStarted": "Начат",
  "detail.noExecution": "Ещё не запускалась",
  "detail.noSession": "Сессии нет",
  "detail.prompt": "Промпт запуска",
  "detail.rerun": "Запустить снова",
  "detail.restore": "Вернуть из архива",
  "detail.result.cancelled": "Отменён",
  "detail.result.failed": "Ошибка",
  "detail.result.running": "Выполняется",
  "detail.result.succeeded": "Успешно",
  "detail.run": "Запустить",
  "detail.schedule": "Запуски по расписанию",
  "detail.schedule.cron": "Выражение cron",
  "detail.schedule.dueSoon": "Скоро",
  "detail.schedule.enable": "Включить запуски по расписанию",
  "detail.schedule.invalid": "Неверное выражение cron",
  "detail.schedule.lastTriggered": "Последний запуск",
  "detail.schedule.nextRun": "Следующий запуск",
  "detail.schedule.notScheduled": "Расписания пока нет",
  "detail.schedule.preset.daily9": "Каждый день в 09:00",
  "detail.schedule.preset.hourly": "Каждый час",
  "detail.schedule.preset.tenMin": "Каждые 10 минут",
  "detail.schedule.preset.weeklyMon9": "По понедельникам в 09:00",
  "detail.schedule.presets": "Готовые варианты",
  "detail.title": "Задача",
  "detail.viewSession": "Открыть сессию",
  "entry.label": "Доска задач",
  "exec.error.noWorkspace": "Нет рабочей папки, в которой можно выполнить задачу",
  "exec.error.promptRejected": "Промпт отклонён",
  "exec.hint": "Применяется при запуске задачи: рабочая папка определяет, где появится сессия выполнения; режим задаёт пресет агента; разрешение выставляется командой /permission. Пусто — как по умолчанию в рантайме.",
  "exec.mode.brokenSuffix": " (недоступен)",
  "exec.mode.default": "Как в установке",
  "exec.mode.defaultSuffix": " (по умолчанию)",
  "exec.mode.removed": " (удалён)",
  "exec.permission.danger-full-access": "Полный доступ",
  "exec.permission.default": "Как в сессии",
  "exec.permission.read-only": "Только чтение",
  "exec.permission.workspace-write": "Запись в рабочую папку",
  "exec.workspace.recent": "Последняя (по умолчанию)",
  "new.cancel": "Отмена",
  "new.description": "Описание",
  "new.descriptionPlaceholder": "Контекст, границы, критерии приёмки (необязательно)",
  "new.mode": "Режим",
  "new.permission": "Разрешения",
  "new.prompt": "Промпт запуска",
  "new.promptPlaceholder": "Полная инструкция агенту (если пусто, возьмётся заголовок)",
  "new.required": "Нужен заголовок",
  "new.submit": "Создать",
  "new.title": "Заголовок",
  "new.titlePlaceholder": "Что нужно сделать, одной строкой",
  "new.workspace": "Рабочая папка",
  "run.failed": "Запуск не удался: {error}",
  "settings.announceToAgent": "Сообщать агентам о доске задач",
  "settings.announceToAgentHint": "Включено: в системный промпт каждого агента добавляется упоминание доски. Выключено: агенты узнают о ней, только если вы скажете сами.",
  "settings.collapse": "Скрыть настройки",
  "settings.description": "Настройка доски задач на хосте, упоминания в промпте и защиты от засыпания, пока есть незавершённая работа.",
  "settings.discard": "Отменить",
  "settings.enabled": "Включить доску задач",
  "settings.enabledHint": "Когда выключено, пункт в панели и сама доска скрыты.",
  "settings.expand": "Показать настройки",
  "settings.inherit": "Наследовать",
  "settings.invalidNumber": "Введите число или оставьте пустым, чтобы взять значение по умолчанию.",
  "settings.notExposed": "Эта версия DSH не выводит namespace настроек плагина на страницу конфигурации, поэтому форма недоступна. Правьте ~/.dsh/settings.yaml напрямую или добавьте namespace в список WEB_SETTINGS_NAMESPACES у dsh-host-apiproxy и перезапустите.",
  "settings.off": "Выкл",
  "settings.on": "Вкл",
  "settings.overridden": "Переопределено",
  "settings.powerBoundary": "Батарея будет расходоваться быстрее. Закрытие крышки, ручной уход в сон, гибернация, выключение, действия при низком заряде и корпоративные политики под гарантию не попадают; уже спящий компьютер не разбудят.",
  "settings.powerError": "Последняя ошибка защиты от засыпания: {error}",
  "settings.powerStatus": "Платформа: {platform}; защита: {phase}; работающих сессий: {running}; включённых расписаний: {schedules}",
  "settings.powerUnknown": "неизвестно",
  "settings.preventIdleSleep": "Не давать системе засыпать",
  "settings.preventIdleSleepHint": "По умолчанию выключено. Когда включено, хост не даёт системе уйти в сон, пока работает хоть одна сессия DSH, включено расписание или состояние сессий ещё неизвестно. Экран при этом может гаснуть.",
  "settings.readOnly": "В этой установке настройки доступны только для чтения.",
  "settings.reset": "Вернуть по умолчанию",
  "settings.save": "Сохранить",
  "settings.saveFailed": "Установка не приняла эти значения; они оставлены, чтобы вы их поправили.",
  "settings.saving": "Сохранение…",
  "settings.title": "Доска задач",
  "settings.unsaved": "Не сохранено",
  "status.move.backlog": "В бэклог",
  "status.move.todo": "К выполнению",
  "time.justNow": "только что"
 },
 "trajectory": {
  "toolbar.actualTime": "Реальное время",
  "toolbar.aria": "Панель траектории",
  "toolbar.calls": "Вызовы",
  "toolbar.collapseCalls": "Свернуть вызовы",
  "toolbar.collapseTurns": "Свернуть ходы",
  "toolbar.duration": "Длительность",
  "toolbar.expandCalls": "Развернуть вызовы",
  "toolbar.expandTurns": "Развернуть ходы",
  "toolbar.search": "Поиск по траектории",
  "toolbar.searchPlaceholder": "Поиск",
  "toolbar.turns": "Ходы",
  "toolbar.useActualDuration": "По реальной длительности",
  "toolbar.useEqualWidth": "Операции равной ширины",
  "view.trajectory": "Траектория"
 },
 "usageDashboard": {
  "buckets.cacheRead": "Чтение кэша",
  "buckets.cacheWrite": "Запись в кэш",
  "buckets.caption": "Четыре непересекающиеся корзины тарификации · всего {total} ток",
  "buckets.output": "Выход",
  "buckets.title": "Состав токенов",
  "buckets.uncachedInput": "Вход мимо кэша",
  "composition.caption": "Оценка по эвристике, не по счёту; в сумму занятости не сойдётся",
  "composition.messages": "Сообщения",
  "composition.system": "Системный промпт",
  "composition.title": "Состав контекста",
  "composition.tools": "Схемы инструментов",
  "efficiency.llm": "Время модели",
  "efficiency.steps": "Шаги",
  "efficiency.stepsValue": "{steps}",
  "efficiency.throughput": "Скорость выдачи",
  "efficiency.title": "Эффективность запросов",
  "efficiency.tool": "Время инструментов",
  "efficiency.ttft": "Первый токен, среднее",
  "efficiency.ttftOver": "шагов: {steps}",
  "efficiency.turns": "Ходы",
  "efficiency.turnsValue": "{turns}",
  "empty.usage": "Расхода токенов пока нет",
  "empty.usageHint": "Цифры появятся, когда сессия сделает первый запрос к модели.",
  "overview.billedInput": "Оплаченный вход",
  "overview.billedInputSub": "мимо кэша {uncached} · из кэша {cached}",
  "overview.cacheHit": "Попадания в кэш",
  "overview.cacheHitSub": "прочитано {read} из {total} ток",
  "overview.context": "Контекст занят",
  "overview.contextSub": "{used} из {window} ток",
  "overview.contextUnknown": "Размер окна модели неизвестен",
  "overview.output": "Выход",
  "overview.outputSub": "всего {total} ток",
  "scope.aria": "Охват статистики",
  "scope.session": "Эта сессия",
  "scope.sessions": "Все сессии",
  "sessions.currentTag": "Текущая",
  "sessions.detail.noData": "Данные по этой сессии загружаются или их нет",
  "sessions.detail.title": "Подробности сессии",
  "sessions.empty": "Расход по сессиям не записан",
  "sessions.inactive": "Простаивает",
  "sessions.running": "Работает",
  "sessions.selectHint": "Выберите строку, чтобы посмотреть сессию",
  "sessions.subagentTag": "Субагент",
  "sessions.summary.input": "Оплаченный вход, всего",
  "sessions.summary.output": "Выход, всего",
  "sessions.summary.sessions": "Сессий с расходом",
  "sessions.summary.sessionsValue": "{count}",
  "sessions.summary.totalValue": "всего сессий: {count}",
  "sessions.summary.turns": "Ходов всего",
  "sessions.summary.turnsValue": "{turns}",
  "sessions.table.cacheHit": "Попаданий в кэш",
  "sessions.table.input": "Оплаченный вход",
  "sessions.table.output": "Выход",
  "sessions.table.session": "Сессия",
  "sessions.table.status": "Состояние",
  "sessions.table.turns": "Ходы",
  "sessions.table.updated": "Изменена",
  "steps.cacheRead": "Кэш Ч",
  "steps.cacheWrite": "Кэш З",
  "steps.caption": "Только загруженное окно, новые сверху; итог считает то же окно",
  "steps.done": "Готово",
  "steps.empty": "В загруженном окне шагов нет",
  "steps.input": "Вход",
  "steps.interrupted": "Прервано",
  "steps.model": "Модель",
  "steps.output": "Выход",
  "steps.reasoning": "Рассуждения",
  "steps.sortBy": "Сортировать по «{column}»",
  "steps.status": "Состояние",
  "steps.title": "Подробности по шагам",
  "steps.tps": "ток/с",
  "steps.ttft": "Первый токен",
  "steps.turn": "Ход.шаг",
  "steps.windowTotal": "Итог по окну",
  "time.daysAgo": "{n} дн назад",
  "time.hoursAgo": "{n} ч назад",
  "time.justNow": "только что",
  "time.minutesAgo": "{n} мин назад",
  "view.usage": "Статистика"
 },
 "workflowRun": {
  "member.empty": "Пустое имя участника",
  "member.open": "Открыть {name}",
  "phase.empty": "Пустое имя фазы",
  "phase.unassigned": "Вне фаз",
  "run.empty": "Ни один участник не запущен",
  "run.members.one": "{count} участник",
  "run.members.other": "{count} участников",
  "run.title": "{name}",
  "status.cancelled": "Отменено",
  "status.completed": "Завершено",
  "status.failed": "Ошибка",
  "status.interrupted": "Прервано",
  "status.running": "Работает",
  "statusCount.cancelled": "Отменено: {count}",
  "statusCount.completed": "Завершено: {count}",
  "statusCount.failed": "Ошибок: {count}",
  "statusCount.interrupted": "Прервано: {count}",
  "statusCount.running": "Работает: {count}"
 },
 "workspace": {
  "actions.newSession.aria": "Новая сессия в {name}",
  "actions.session.aria": "Действия с сессией {name}",
  "actions.workspace.aria": "Действия с рабочей папкой {name}",
  "conflict.named": "Рабочая папка «{name}» уже есть.",
  "date.ymd": "{d}.{m}.{y}",
  "delete.desc": "Уберёт «{name}» из списка рабочих папок. Сама папка и журналы сессий останутся, а её сессии переедут в «Без папки».",
  "delete.pending": "Удаление рабочей папки…",
  "delete.workspace": "Удалить рабочую папку",
  "empty.noMatches": "Ничего не найдено",
  "empty.none": "Сессий пока нет",
  "field.sessionName": "Название сессии",
  "field.workspaceName": "Название рабочей папки",
  "folderError.retry": "Выбрать снова",
  "folderError.title": "Не удалось открыть папку",
  "group.ungrouped": "Без папки",
  "groupBy.flat": "Одним списком",
  "groupBy.label": "Группировать",
  "groupBy.workspace": "По рабочим папкам",
  "hover.copied": "Скопировано",
  "hover.created": "Создано {time}",
  "menu.addWorkspace": "Добавить рабочую папку…",
  "menu.archiveSession": "Убрать сессию в архив",
  "menu.fork": "Ответвить сессию",
  "orderBy.label": "Сортировать",
  "orderBy.manual": "Вручную",
  "orderBy.updated": "По изменению",
  "picker.loading": "Загрузка рабочих папок…",
  "rename": "Переименовать",
  "rename.session.title": "Переименовать сессию",
  "rename.workspace.title": "Переименовать рабочую папку",
  "search.clear": "Очистить поиск",
  "search.hasMore": "Показаны первые {n} результатов. Уточните запрос.",
  "search.noMatches": "Подходящих сессий нет",
  "search.pending": "Поиск по истории сессий…",
  "search.placeholder": "Поиск по сессиям...",
  "search.results.aria": "Результаты поиска",
  "search.sessions.aria": "Поиск сессий",
  "search.unavailable": "Поиск по содержимому временно недоступен. Показаны совпадения по названию.",
  "section.sessions": "Сессии",
  "section.workspaces": "Рабочие папки",
  "session.new": "Новая сессия",
  "sessions.collapse": "Показать меньше",
  "sessions.count.one": "{n} сессия",
  "sessions.count.other": "{n} сессий",
  "sessions.expand": "Показать ещё {n}",
  "status.completed": "Завершено",
  "status.idle": "Простаивает",
  "status.planReview": "План ждёт проверки",
  "status.running": "Работает",
  "status.subagentsRunning.one": "{n} субагент работает",
  "status.subagentsRunning.other": "{n} субагентов работает",
  "status.waitingAnswer": "Ждёт ответа",
  "status.waitingApproval": "Ждёт подтверждения",
  "time.ago": "{t} назад",
  "time.days": "{n} дн",
  "time.hours": "{n} ч",
  "time.minutes": "{n} мин",
  "time.months": "{n} мес",
  "time.now": "только что",
  "time.years": "{n} г",
  "viewOptions.label": "Параметры отображения",
  "workspace.add": "Добавить рабочую папку"
 }
}

    const SETTINGS_NS_NAME = 'russianLang'

    const CSS = ".drl-row{border-bottom:1px solid var(--dsw-alias-border-l2);align-items:center;gap:8px;padding:16px 0;display:flex}.drl-text{flex-direction:column;flex:1;gap:4px;min-width:0;padding-right:48px;display:flex}.drl-title{color:var(--dsw-alias-label-primary);font-size:14px;font-weight:400;line-height:22px}.drl-sub{color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px}.drl-switch{background:var(--dsw-alias-bg-module-platform);height:36px;font:inherit;color:var(--dsw-alias-label-primary);cursor:pointer;border:none;border-radius:18px;align-items:center;gap:10px;padding:0 14px;font-size:14px;line-height:22px;display:inline-flex}.drl-switch:hover{background:var(--dsw-alias-interactive-bg-hover)}.drl-knob{width:14px;height:14px;border-radius:50%;background:var(--dsw-alias-label-tertiary);flex:none}.drl-on .drl-knob{background:var(--dsw-alias-state-success-primary)}"

    function apply(ctx) {
      // 1. Словари: каждый namespace — свой эффект, словарь снимается вместе с
      // плагином. Если namespace уже несёт ru (плагин локализовался сам) —
      // не конфликтуем.
      for (const ns of Object.keys(RU)) {
        ctx.effect(() => {
          try { return ctx.locale.register(ns, 'ru', RU[ns]) }
          catch (err) { return () => {} }
        }, 'dsh-russian-lang: ' + ns)
      }

      const coreHasRu = () => {
        try { return ctx.locale.getLocale().locales.some((l) => l.id === 'ru') }
        catch (err) { return false }
      }

      // Штатный путь, если ядро знает ru; иначе публичный publish.
      const activate = (id) => {
        try {
          if (coreHasRu()) ctx.locale.setLocale(id)
          else ctx.locale.publish(id, true)
        } catch (err) { console.warn('dsh-russian-lang: switch failed', err) }
      }

      // 2. Настойка-переключатель: читаем сохранённое enabled через штатный
      // settings scope и включаем русский на старте.
      const scope = ctx.settingsScope.bind({ namespace: SETTINGS_NS_NAME })
      let booted = false
      const tryBoot = () => {
        if (booted) return
        try {
          const value = scope.getSnapshot().value
          if (value && value.enabled === true) { booted = true; activate('ru') }
        } catch (err) { /* снимок ещё не готов — догоним по subscribe */ }
      }
      ctx.effect(() => scope.subscribe(tryBoot), 'dsh-russian-lang: boot')
      tryBoot()

      // 3. <html lang>: в таблице DOCUMENT_LANGUAGE ядра нет "ru" и без нас там
      // окажется undefined. Поправляем после каждого переключения (наш слушатель
      // зарегистрирован позже ядерного и перекрывает его запись).
      const syncLang = () => {
        try {
          if (typeof document !== 'undefined' && document.documentElement
              && ctx.locale.getLocale().active === 'ru') {
            document.documentElement.lang = 'ru'
          }
        } catch (err) { /* ignore */ }
      }
      ctx.effect(() => ctx.locale.subscribe(syncLang), 'dsh-russian-lang: html-lang')
      syncLang()

      // 4. Строка «Русский язык» в Настройки -> Общие (тот же слот, где живёт
      // ядерная строка Language). Состояние держим сами: ядро не знает про ru,
      // его store нам не подходит.
      if (typeof document !== 'undefined' && !document.querySelector('style[data-plugin-css="dsh-russian-lang"]')) {
        const tag = document.createElement('style')
        tag.setAttribute('data-plugin', 'dsh-russian-lang')
        tag.dataset.pluginCss = 'dsh-russian-lang'
        tag.textContent = CSS
        document.head.appendChild(tag)
      }

      function RussianRow() {
        const isActive = () => {
          try { return ctx.locale.getLocale().active === 'ru' }
          catch (err) { return false }
        }
        const [on, setOn] = React.useState(isActive)
        React.useEffect(() => {
          const update = () => setOn(isActive())
          try { return ctx.locale.subscribe(update) }
          catch (err) { return undefined }
        }, [])

        const toggle = () => {
          if (on) {
            booted = false
            try { scope.set('enabled', false) } catch (err) { /* ignore */ }
            activate('en')
          } else {
            try { scope.set('enabled', true) } catch (err) { /* ignore */ }
            activate('ru')
          }
        }

        return React.createElement('div', { className: 'drl-row' },
          React.createElement('div', { className: 'drl-text' },
            React.createElement('div', { className: 'drl-title' }, 'Русский язык'),
            React.createElement('div', { className: 'drl-sub' },
              on ? 'Перевод интерфейса включён' : 'Перевод интерфейса выключен')),
          React.createElement('button', {
            type: 'button',
            className: 'drl-switch' + (on ? ' drl-on' : ''),
            'aria-pressed': on,
            onClick: toggle
          },
            React.createElement('span', { className: 'drl-knob' }),
            React.createElement('span', null, on ? 'Вкл' : 'Выкл')))
      }

      ctx.slots.inject('settings.general.item', () => ctx.slots.register({
        name: 'settings.general.item',
        id: 'dsh-russian-lang',
        order: 1,
        inject: () => ({})
      }, RussianRow))
    }

    module.exports = { apply, inject: ['slots', 'locale', 'connection', 'remote', 'settingsScope'] }
    return module.exports
  },
})
